#ifndef _ENGLISHWORD_H
#define _ENGLISHWORD_H

// 考研英语高频词汇

#include <string>
using namespace std;
const char* EnglishWord[] = {
  "rape n.强奸；破坏，蹂躏 vt.强奸；破坏，蹂躏",
"rash	deliberate  n.皮疹",
"guideline		 n.指导方针，指导原则，准则，标准",
"gut	胆量；内脏a.本能的vt.取出内脏",
"refund		  n.v. 退款；赔偿",
"relish		   n.喜好，乐趣；美味；胃口 v.爱好，喜欢",
"remnant		 n.残余，剩余；残余物，残存部分",
"renaissance	文艺复兴(时期)；新生，复兴",
"habitat		   n.(动物的)栖息地，(植物的)产地",
"harassment		 n.骚扰，扰乱；烦恼，烦乱",
"recycle		 vt./vi.重复利用(用过的物资)，循环使用",
"redundant		 a.被解雇的；多余的，过剩的",
"refugee		 n.(政治上的)避难者，难民",
"ritual		    a.宗教仪式的，典礼的 n.仪式，典礼；惯例",
"robust		a.强健的，茁壮的；有力的  [反",
"salvation		n.(尤指基督)救世，超度；拯救，解困",
"sanction		v.同意(某事)，批准，认可 n.批准,国际制裁",
"repression		 n.压抑，压制，镇压",
"sane		    a.心智健全的，神志清醒的；明断的，理智的",
"sarcastic		a.讽刺的，嘲笑的，挖苦的",
"saturate		vt.使湿透，浸透；使充满，使饱和",
"repertoire		n.全部剧目,保留剧目,全部技能",
"retention		n.保留；保持；记忆(力",
"retort		n.v.报复；反击；反驳",
"boost  n.促进，激励；一抬；一推 vt.推动，增强",
"bowel  n.肠；［pl.］内部，深处",
"retrieve		  vt.重新得到，取回；挽回，补救；检索",
"retrospect		v.n.回顾，回想，追溯[反",
"revelation		n.揭示，透露，显示；被揭示的真相，新发现",
"rigorous		 a.严格的，严厉的，严酷的(气候条件",
"riot		    n.暴(骚)乱；(色彩等)极度丰富vi.聚众闹事",
"rip		    v.猛撕开；扯开；被撕开；裂开",
"scandal		 n.丑事，丑闻；流言蜚语；反感，愤慨",
"scramble		vi.(快速地)爬，攀登；互相争夺，争先",
"siege		   n.包围，围攻，围困",
"sip		  v.小口地喝，抿，呷  n.一小口的量",
"sceptical/skeptical		 a.怀疑的",
"skim		   vt.撇去(液体表面)之漂浮物 vi.轻轻掠过",
"skip		    vi.略过，跳过 n.跳跃 vt.故意忽略；略过",
"fridge		  n.(refrigerator的略语)冰箱",
"radiant		a.(面容、目光)洋溢着幸福的，明亮照耀的",
"rap		    vt.急敲；突然厉声说出；训斥n.急敲(声",
"thermal		热的，由热造成的",
"texture		  n.(织物)质地；(材料)构造；结构；肌理",
"transcend		 vt. 超出，超越(理性等)的范围",
"abolish		   彻底废除（法律、制度、习俗等",
"prime		   首要的，主要的",
"foul		   a. 令人不快的；恶臭的；邪恶的 v.弄脏 n.(体育等)犯规",
"thirst		    渴，口渴",
"trail		痕迹，足迹",
"tramp		步行，跋涉",
"transfer		  转移，调动",
"fringe		 n.边缘；(窗帘)缘饰；额前垂发 vt.饰…的边",
"fume		n.(usu pl.)（浓烈或难闻的）烟，气，汽",
"blur		   n.模糊不清的事物 vt.使模糊，使看不清楚",
"browse		vi.随意翻阅，浏览；(牛、羊等)吃草",
"primitive		原始的，上古的，早期的",
"prior		在先的，在前的",
"privilege		 n 特权，优惠，特免",
"probe		 vt .  探索，探查，调查",
"verify		 vt.   证明",
"vertical		 adj. 垂直的，立式的",
"veto		 n. 否决，否决权，否决权的行使",
"absolute		 adj  纯粹的，完全的",
"verge		 n 边，边缘，边沿",
"accustom		  vt. 使习惯",
"acquaint		 vt. 使认识，使了解",
"trash		 n.垃圾；拙劣的作品；渣滓，败类vt.捣毁",
"toxic		 adj.有毒的，因中毒引起的",
"amaze		 vt. 使惊愕，使惊异",
"breach		 n.违反，不履行；破裂 vt.冲破，攻破",
"briefcase		 n.手提箱，公事皮包",
"ambiguous		 adj.含糊不清的，模棱两可的",
"ozone		 n. 臭氧；清新的空气",
"script		 n.剧本(原稿)；手稿，原稿；笔迹，手迹",
"scrutiny		 n.周密的调查；仔细看；监视；选票复查",
"sculpture		 n.雕刻(术)，雕塑(术)；雕刻作品",
"pact		 n.合同，条约，公约",
"trace		 n. 痕迹，踪迹",
"track		 n.足迹，踪迹",
"tragedy		 n. 悲剧",
"paperback		 n.平装本，简装本",
"tame		 adj.驯化的，驯服的，温顺的",
"tan		 n.棕黄色，黄褐色",
"tax		 n.税（款",
"abrupt		adj.  突然的，意外的",
"acute		 adj.尖锐的，敏锐的",
"versatile		 adj. 多才多艺的",
"versus		 prep.(介词)诉讼，竞赛等中以…为对手",
"blunt		 adj.钝的",
"Blush		 （因害羞、激动、窘困）脸红",
"abide		 vt.遵循（…by）；容忍",
"delight		 n. 高兴，快乐",
"deliver		 vi. 投递，传送，运输",
"demonstrate		 vt.论证，证明",
"accelerate		 vt. 加速，增速",
"thread		 n.线，线状物",
"thrill		 vt.使非常兴奋，使非常激动",
"thrive		 vi.兴旺发达，繁荣",
"abuse		n. vt.  滥用",
"stream		 n. 小河，溪流",
"stress		n.压力，紧张",
"stretch		 v. 伸直，伸长",
"stride		 vt.& vi. 阔步前进，大踏步走",
"temper		 n. 心情，脾气",
"tempt		 vt.  引诱，诱惑",
"strain		 vt.& vi 拉紧，绷紧",
"strap		 n. 带，皮带",
"strike		 vi.打击，撞",
"string		 n.细绳，线，带",
"strip		 vi.&vt剥去，除去",
"access		 n.入口，出口; 接近，进入;接近（或进入）的机会",
"tip		 末端，尖端",
"toast		 n.干杯;烤面包，吐司",
"token		 n.&vt.表示，标志，象征",
"torture		 n.&vt拷打，拷问",
"accommodate		 vt.使适应，使符合一致",
"unfold		 vt.& vi. 展开，打开",
"uniform		 n.制服；adj.不变的，相同的，均匀，统一的",
"unify		 vt.使成一体，统",
"adhere		 vi&vt  黏附，附着",
"adjacent		adj.  临近的，毗邻的",
"adjoin		 vt.& vi.  贴近，与...毗邻",
"thrust		 vt.& vi推，刺，戳，插，挤",
"update		 vt. 更新，使现代化",
"upgrade		 vt. 提高，使升级，改善",
"uphold		vt. 举起，高举",
"upright		 adj. 挺直的，垂直的",
"tick		 n.（钟声等发出的）滴答声",
"tilt		vt&vi.使倾斜，使倾倒",
"toss		 vt.& vi. 扔，抛，掷",
"tough		adj. 坚韧的，牢固的",
"tow		vt.拖，拉，牵引",
"abstract		 adj. 抽象的",
"absurd		adj. 荒谬的，荒唐的",
"uproar		n. 骚乱，骚动",
"utilize		vt.利用",
"utter		vt. 发出（声音等），说，吐露",
"vacant		 adj. 未被占用的",
"vague		adj. 含糊的，不明确的，模糊的",
"slip		 vi&vt. 滑倒，滑落，滑行",
"slit		vt. 切开，撕开",
"slope		vi. 倾斜，有坡度",
"impact		 n. 冲击，撞击 vt.挤入，压紧; 撞击; 对…产生影响",
"impair		 vt.削弱，减少",
"impartial		adj. 公正的，无偏见的",
"implement		n.工具，器具，用具",
"sly		 adj.狡猾的，偷偷的",
"smash		 vt. 打碎，打破，摧毁",
"snatch		 vt. 夺得，一把抓住",
"immune		 adj.免除的，豁免的",
"sting		 vt.&vi刺，螫，叮",
"stir		 vt.& vi.使微动，移动",
"stitch		 n.一针，针脚",
"sue		 vt.& vi控告，起诉",
"summary		 n. 总结，概要",
"superb		 adj. 极好的，一流的，杰出的",
"superficial		adj.表面的",
"superfluous		adj.过多的，剩余的，多余的",
"ventilate		 vt.使通风，使空气流通",
"venture		n.冒险，冒险行动，投机行动",
"uncover		 vt. 揭开，揭露",
"supervise		 vt.& vi 监督，管理，指导",
"vanish		 vi.突然消失，逐渐消散",
"veil		 n. 面纱，面罩",
"underestimate		 低估",
"reassure		 v.使安心，使放心；使消除疑虑",
"recede		 v.退去；缩进；收回，撤回 [反",
"recipient		 n.收到者",
"reckless		 a.不注意的,大意的,卤莽的,不顾后果的",
"rectangle	矩形, 长方形",
"recur		 v.(尤指不好的事)一再发生；重现",
"portray		 v.描写，描述；画(人物、景象等",
"prone		 a.(to)易于…的，很可能…的；俯卧的",
"prophet		 n.预言家；先知；提倡者",
"undergo		vt.经历，遭受，忍受",
"underlie		 vt. 位于……之下",
"undermine		 v. 在……下挖",
"undertake		 vt. 着手做， 从事",
"undesirable		adj. 不合意的，不受欢迎的",
"uneasy		adj. 心神不宁的，不安宁的",
"accord		 vt. 使符合，相一致",
"account		n.记述，叙述",
"address		 n.地址;  演说",
"ultimate		 adj.最后的，最终的",
"unanimous		adj.全体一致的，一致同意的",
"virtue		 美德，德行",
"visible		adj. 看得见的，可见的",
"vision		n.视力，视觉",
"substitute		 n.代替者，代替物",
"subtle		adj.微妙的，巧妙的",
"subtract		 vt.减，减去",
"succession		n.连续，一系列",
"suck		 vt. 吸",
"vital		 adj.维持生命所必需的;有生命力的",
"vivid		adj.鲜艳的",
"void		 adj.空的",
"wedge		n.楔子，三角木",
"weed		n.杂草，野草",
"weep		 vt.& vi.（通常因悲伤）哭泣，流泪",
"weigh		 vt.称……重量，称",
"Xerox		n.静电复印（法），静电复印件，静电复印机",
"yield		vt.生产，产生，带来",
"zeal		 n.热心，热忱，热情",
"vicious		adj.邪恶的，恶毒的，凶残的",
"volunteer		n.志愿者，自愿参加者",
"Zigzag		adj.之字形的，弯曲的",
"Wander		vt.&vi漫步，徘徊",
"ward		n. 病房",
"warrant		n.授权，批准，正当理由，根据",
"waterproof		adj. 不透水的，防水的",
"whisper		 vt.低语，耳语，轻声说",
"audit		 v.审计；查帐；核对；旁听",
"vibrate		 vt.& vi.使震动，使摆动",
"weld		 vt.& vi.焊接，煅接",
"whirl		vi.&vt旋转，急转",
"audio		 n./a.音频(响)(的)；声音(的)，听觉(的",
"auditorium		 n.观众席，听众席；会堂，礼堂",
"stab		 vt.&n.刺，戳，猛的一击，突发的一阵",
"stack		n.整齐的一叠",
"stain		vt&vi玷污，污染",
"stale		adj. 食品等不新鲜的，走味的",
"stall		 n.小隔间;牛舍",
"startle		vt.惊吓，使吃惊",
"starve		 vi.&vt.使挨饿，饿死",
"addict		 v.使沉溺；使上瘾 n.沉溺于不良嗜好的人",
"advent		 n.(重要事件等的)到来，来临",
"affluent		 a. 富裕的，富足的",
"bait		 n.饵，引诱物 vt.用饵引诱；招惹，捉弄",
"balcony		 n.阳台；(电影院等的)楼厅，楼座",
"ballet		 n.芭蕾舞，芭蕾舞剧；芭蕾舞团",
"stock		 n.原料，备料，库存，现货",
"stoop		 vt.& vi.&n. 俯身，弯腰",
"statistics		 n.统计，统计资料",
"steer		 vt.& vi.掌舵，驾驶",
"authentic		 a.真的，真正的；可靠的，可信的，有根据的",
"awe		 n.敬畏，惊惧vt.使敬畏，使惊惧",
"bizarre		 adj.异乎寻常的，稀奇古怪的",
"stubborn		adj.顽固的，倔强的",
"stuff		n.原料，材料，物品，东西",
"subject		n.题目，主题",
"submerge		 vt.& vi.浸没，淹没，湮没",
"submit		vt.屈服，服从，投降",
"anguish		 n.(尤指心灵上的)极度痛苦，烦恼",
"antique		 a.古式的，过时的　n.有价值的古物，古董票",
"Barbecue		 n.烤肉用的台架；烤肉野餐 vt.在台架上烤肉",
"appall		 v.使胆寒,使惊骇",
"wrap		vt.包，裹",
"wreck		n.失事，遇难",
"wrench		n.扳手",
"ballot		 n.(不记名)投票；投票总数；投票权 vi.投",
"barren		 a.贫瘠的；不育的；(植物)不结果的；无用的",
"belly		 n.肚子，腹部；(像肚子一样)鼓起的部分，膛",
"benign		 a.(病)良性的,(气候)良好的,仁慈的,和蔼的",
"beverage		 n.(水，酒等之外的)饮料",
"bin		 n.(贮藏食物等用的)箱子",
"wrinkle		n.皱，皱纹",
"write		写，写字，写信，写作",
"album		 n. 唱片;集邮册,相册",
"storm		n.风暴，暴风雨，暴风雪",
"straightforward		adj.一直向前的，直接的",
"subordinate		adj.下级的",
"substance		n.物质，实质",
"air-conditioning		 n.空调设备，空调系统",
"stationary		adj.固定的，静止的，非流动的",
"amiable		  a.和蔼可亲的，友善的，亲切的",
"amid		 prep.在…中间，在…之中，被…围绕",
"auction		 n.／vt.拍卖",
"endow		 vt.资助，捐赠；(with)给予，赋予",
"escalate		 v.(使)逐步增长(或发展)，(使)逐步升级",
"escort		 vt.护送(卫)；陪同 n.警卫，护送者；仪仗兵",
"evade		 vt.逃避，回避；避开，躲避",
"arrogant		 a.傲慢的，自大的",
"artery		 n.动脉；干线，要道",
"blueprint		 n.蓝图，设计图，计划 vt.制成蓝图，计划",
"ego		 n.自我，自负，利已主义；(心理学)自我意识",
"eligible		 a.有条件被选中的；(尤指婚姻等)合适(意)的",
"aspire		 vi.(to，after)渴望，追求，有志于",
"assassinate		 vt.暗杀，行刺；中伤",
"waken		vi&vt.醒来，睡醒",
"virtual		adj.实际上的，事实上的",
"weary		adj.疲倦的，疲劳的",
"vigor		n.体力，精力，活力",
"violate		 vt.违反，违背",
"zone		n.地带，分布带",
"abdomen		 n.腹，下腹(胸部到腿部的部分",
"abound		 vi.大量存在；(in，with)充满，富于",
"acclaim		 v.向…欢呼，公认 n.欢呼，喝彩，称赞",
"accountant		 n.会计人员，会计师",
"aisle		 n.(教堂、教室、戏院等里的)过道，通道",
"supplement		n.增补，补充",
"Suppress		 vt.压制，镇压",
"Supreme		adj.最高的，至上的",
"Surpass		vt.超过，优于，强于，胜过",
"Surplus		n.过剩，剩余",
"Survey		vt.调查",
"asset		 n.(pl.)资产(产)；有用的资源；优点，益处",
"blackmail		 n.讹诈，敲诈，勒索；胁迫，恫吓",
"blade		 n. 刀刃，刀片；桨叶，桨片；草叶，叶片",
"blouse		 n.女衬衣，短上衣，宽阔的罩衫",
"vain		adj.徒劳的，无效的",
"valid		adj.有根据的",
"value		n.价值",
"foster		 vt. 照管；培养；促进",
"bruise		 n.青肿，挫伤；伤痕vt.打青；挫伤",
"bully		 n.恃强欺弱者，小流氓 vt.威胁，欺侮",
"bureaucracy		 n.官僚主义，官僚机构；(非民选的)委任官员",
"burglar		 n.(入室行窃的)盗贼",
"cape		 n.海角，岬；披肩，短披风",
"carbohydrate		 n.碳水化合物; 糖类；(plural)淀粉质或糖类",
"celebrity		 n.名人，名流；著名，名声，名望",
"Christ		 n.基督，救世主，耶稣",
"clergy	牧师，神职人员",
"coalition		 n.结合体，同盟；结合，联合",
"costume		 n. 戏装；泳装；服装",
"cosy/cozy	 a.暖和舒服的；舒适的 [反",
"credentials		 n.(个人能力及信用的)证明书，证件",
"glamour		 n.魔力，魅力 vt.迷住",
"strenuous		 a.费力的，艰辛的；奋发的，努力的",
"ebb		 vi.衰退，减退,（指潮水）退; n.处于低潮，处于衰退状态",
"eccentric		 a.古怪的，怪癖的，异乎寻常的n.古怪的人",
"futile		 a.无效的，无用的，无希望的",
"gender		 n.(生理上的)性；(名词、代词等的)性",
"strife		 n.争吵；冲突，斗争；竞争",
"stroll		 n.&v.漫步；散步；游荡",
"gorgeous		 a.华丽的；灿烂的；美丽的；宜人的；棒的",
"graphic		 a.生动的，形象的；绘画的，文字的，图表的",
"medieval		 a. 中世纪的",
"excel		 vi.(at，in)突出，擅长vt.胜过，优于",
"excerpt		 n.摘录，节录 vt.摘，引用",
"layoff		 n.临时解雇；关闭；停歇",
"lottery		 n.抽彩；碰运气的事，难于算计的事",
"majesty	雄伟，壮丽，庄严",
"manoeuvre	 vi.熟练地进入",
"exile		 n.流放；被流放者 vt.流放，放逐，把…充军",
"fairy		 adj.幻想中的，虚构的",
"feat		 n.功绩，伟业，技艺",
"federation		 n.联合会；结盟，联合",
"fore		 ad.在前面 a.先前的；在前部的 n.前部",
"solitary		 a.(好)孤独的；偏僻的；单一的，唯一的",
"solo		 n.独奏 a. ad.单独的(地)；独唱的(地",
"spiral		 a.螺旋形的 n.螺旋，螺线 v.螺旋上升；盘旋",
"spouse		 n. a  wife or husband 配偶",
"stagger		 vi.摇晃着移动;蹒跚 n.摇晃不稳的动作;蹒跚",
"stalk		 n.茎，梗vt.悄悄地跟踪vi.高视阔步地走",
"staple		 n.主要产品；名产；纤维；主要成分，主食",
"statute		 n.成文法，法令，法规；章程，规则，条例",
"steak		 n.牛排；大块肉(或鱼)片",
"suffice		 v.足够，(食物)满足",
"suite		 n.套间；一套家具；套，组，系列",
"summit		 n.顶，最高点；颠峰，高峰；最高级会议",
"superstition		 n.迷信，迷信的观念习俗",
"oxide		 n. 氧化物",
"stereotype		 n.陈规，老套，模式化 vt.使定型，使模式化",
"formidable	 or deal with 难对付的；可怕的",
"meditate		 v.认真思考，沉思；计划，考虑",
"momentum		 n. 动量；动力；势头",
"monarch		 n.帝王，君主，最高统治者",
"motivate		 vt.促动；激励，鼓励，作为…的动机",
"nightmare		 n.恶梦；可怕的事物，无法摆脱的恐惧",
"optimum		 a.最适宜的 n.(生长繁殖的)最佳条件",
"option		 n.选择(权)；可选择的事物(或人)，选课",
"overturn		 n. 推翻",
"stun		 vt.使…失去知觉；使目瞪口呆，使吃惊",
"subsidy		 n.补助金；津贴费",
"grim		 a.严酷的，令人害怕的；不愉快的，讨厌的",
"grin		 vi. 露齿笑n.咧嘴笑",
"slaughter		 n.屠杀，屠宰 vt.屠杀，宰杀",
"slot		n.狭缝；空位vt.放入狭缝中；把…纳入",
"sneak		 vi.偷偷地走，溜vt.偷偷地做(或拿、吃",
"sneeze		 vi.打喷嚏，发喷嚏声n.喷嚏",
"agitate		 vi&vt.搅动（液体等",
"grope		 vi.暗中摸，摸索；探索，搜寻vt.摸索",
"heave		 v.(用力)举，提，拉；扔；拖；呕吐n.举起",
"herb		 n.药草，(调味用的)香草，草本植物",
"hierarchy		 n.等级制度；统治集团，领导层",
"hike		  n.徒步旅行；增加vi.徒步旅行vt.提高",
"passerby		 n.过路人，路人",
"pilgrim		 n.最初的移民(P大写，指1620由欧洲移居美国的清教徒",
"plea		 n.(法律)抗辩；请求，恳求，托词，口实",
"skull		 n.头盖骨，颅骨",
"alarm		 n.惊恐，忧虑",
"sort		n. 种类，类别",
"sound		 n.声音，声响; adj.健康的，健全的，完好的",
"sour		adj.酸的，酸味的",
"alert		adj.警惕的，留神的",
"alien		 n.外国人; 外侨;外国的",
"allege		 断言，宣称",
"temperament		 n.气质，性格，性情；资质",
"tropic	热带地区",
"tumour/tumor	  n.(肿)瘤，肿块",
"amateur		 n.（艺术，科学等的）业余爱好者",
"allocate		 vt.分配，分派，把...拨给",
"sniff		 vi.嗅…味道；抽鼻涕；对嗤之以鼻，蔑视",
"soar		 vi.(指鸟等)高飞，翱翔；飞涨；高耸",
"sociable		 a.好交际的，友好的，合群的",
"solidarity		 n.团结；休戚相关",
"surge		 vi.(如浪潮般)汹涌；奔腾 n.(感情等的)洋溢",
"susceptible		 a.过敏的，敏感的；易动感情的，易受感动的",
"tangle		 n.纠缠；缠结；混乱 v.(使)缠绕；变乱",
"ambition		n.（对名利等的）强烈欲望，野心",
"amend		 vt.& vi.修改，修订",
"administrate		v.掌管，料理...的事务",
"adolescent		n.（尤指16岁以下的）青少年",
"advance		 vt.（使）前进;使向前移动",
"sector		 n.部门，部分；防御地段，防区；扇形",
"seemingly		 ad. in appearance; apparently 表面上的，看起来的",
"alternate		 vt.交替，轮流",
"arouse		vt.使......奋发",
"array		n.排列，队形",
"articulate		adj.发音清晰的，善于表达的",
"shatter		 n.碎片；粉碎　v.粉碎；使疲惫；使震骇",
"shove		 vt.乱推；乱塞  vi.用力推，挤  n.猛推",
"shuttle		 n.往返汽车/列车/飞机；穿梭  v.往返穿梭",
"segregate		 vt. separate or keep apart from others  分离，隔离",
"serial		 n.连本影片，连本电视节目 a.连续的",
"setback		 n.挫折；失效；复发；倒退",
"shabby		 a.简陋的，破旧的；卑鄙的，不正当的",
"aggravate		vt.加重，加剧，恶化",
"aggressive		 adj.侵犯的，侵略的",
"allied		adj.结盟的，有关联的",
"allowance		n.津贴，补贴，零用钱",
"alter		 vt.改变，更改",
"adverse		adj.不友好的，敌对的",
"advocate		 vt.拥护，提倡，主张n.提倡者; （辩护）律师; 支持者",
"aesthetic		adj.美学的，艺术的，审美",
"affiliate		 vt.& vi使隶属（或附属）于，使成为会员",
"affirm		 vt.& vi断言，申明",
"artificial		adj.人工的，人造的，人为的",
"ascend		vi&vt.登高，（渐渐）上升，升高",
"ascertain		vt.查明，弄清，确定",
"ashamed		adj.惭愧的，羞耻的",
"ashore		adv.向岸，向陆地",
"aside		 prep在旁边",
"assimilate		vi&vt.吸收，消化",
"associate		vi&vt.（使）联系，（使）结合",
"bar		n.条，块，杆，棒, 酒吧",
"assault		 n.攻击，袭击",
"assemble		 vt.& vi.集合，召集",
"assert		 vt.肯定地说（出），坚定地断言",
"assess		vt.估价，评价，评论",
"assign		vt.分配，布置（作业",
"beforehand		adv.预先，事先",
"bewilder		vt.使迷惑，使糊涂",
"boom		n.低沉有回响的声音",
"bore		vt&vi.钻孔，挖（通道",
"bounce		 vi&vt.弹起，反弹",
"sovereign		 a.独立的，有主权的 n.君主，国王，统治者",
"spacious		 adj.广阔的，宽敞的",
"spectrum		 n.谱，光谱，频谱；范围，幅度，系列",
"spicy		 a.加很多香料的；(口味)浓郁的",
"spine		 n.脊柱，脊椎；(动植物的)刺；书脊",
"bound		vi&vt.跳跃，弹回",
"boycott		vt.（联合起来）抑制，拒绝参加",
"brace		 vt.支撑; n.支持物; 铁钳，托架，支架",
"breed		vt.（使）繁殖",
"bribe		vt&n.贿赂",
"anchor		锚",
"Annoy		 vt.使恼怒，使生气",
"annual		adj.每年的，年度的",
"anonymous		 adj.匿名的，无名的",
"anticipate		 vt.&vi预期，预料",
"apart		 adv.&ad.j成零碎",
"Apparent		 adj.显然的，明明白白的",
"brisk		adj. 轻快的，生气勃勃的",
"brittle		 adj.易碎的，一碰就破的",
"appoint		 vt.任命，委派",
"appraise		 vt.估量，估计",
"appreciate		 vt.感激",
"apprehend		vt&vi对...担心",
"appropriate		adj.恰当的，相称的",
"approve		 vt.& vi赞成，同意",
"accumulate		 vt.& vi积累，积攒，积聚",
"accurate		adj.准确的，精确的",
"accuse		 v.指控，指责",
"activate		 使活动起来，使开始起作用，启动",
"bump		 vt.& vi.碰，撞",
"burst		vi&vt 爆炸，爆裂",
"casual		adj.偶然的，无计划的，随便的，非正式的",
"cease		 vt.&vi.停止，终止，结束",
"certify		 vt.证明，证实",
"challenge		vt.向...挑战",
"character		n.（事物的）性质，特质",
"secure		adj.安全的，可靠的，有把握的",
"sensible		adj.明知的，合情理的",
"approximate		 adj.大概的，大约的，近似的",
"apt		adj.（习性）易于......的，有......倾向的",
"Arbitrary		adj. 随心所欲的，个人武断的，任意的",
"arise		 vi.& vt 起立，起身",
"blaze		 n.火焰",
"aggravate		 vt.加重，加剧，恶化",
"aggressive		adj. 侵犯的，侵略的",
"allied		adj.结盟的，有关联的",
"allowance		n. 津贴，补贴，零用钱",
"alter		vt&vi. 改变，更改",
"charge		 n&vi&vt.要（价），收（费",
"charm		 n.魅力，魔力",
"chase		 vi&vt&n.追逐，追求",
"Check		 vt.使突然停止，制止",
"cherish		vt. 珍爱，珍视",
"chew		 vt.& vi嚼，咀嚼",
"choke		 vt.& vi.窒息，噎住",
"bias		 n.偏见，偏心",
"blame		vt. 责备，责怪",
"blast		n.一阵（风），一股（气流",
"alternate		 vi&vt.交替，轮流",
"arouse		vt. 使......奋发",
"array		排列，队形",
"articulate		 adj.发音清晰的，善于表达的",
"boast		n. 自吹自擂，自夸的话",
"bolt		 n.螺栓，（门，窗的）插销",
"confuse		vt.使混乱，混淆",
"Corrupt		adj.堕落的,腐败的,贪赃舞弊的",
"Count		v.数,计算",
"Course		n.课程,科目",
"courtesy		n.谦恭有礼。有礼的举止（或）言辞",
"credit		n.信任，可信性；学分",
"shade		n.荫，荫凉处",
"sham		n.假装，虚伪",
"shear		vt.&vi剪，修剪",
"shed		流",
"sheer		adj.完全的，十足的",
"shelter		n.掩蔽处，躲避处",
"connect		 vt&vi.连接，连接",
"conscious		adj.意识到的，自觉地",
"consent		vi&n. 同意，赞同，准许",
"conserve		 vt&n.保护，保藏，保存",
"consist		vi.组成，构成",
"consolidate		vt&vi巩固，加强",
"conspicuous		adj显眼的，明显的，引人瞩目的",
"Contrary		adj.相反的,对抗的",
"Contrast		vi&vt对照,对比,(对比之下显出的)差异",
"Contribute		 vt.& vi捐(款等),捐献",
"Contrive		 vt.设计,想出",
"corrode		 vt.& vi. (渐渐)损害,(一点一点地)损伤",
"dawn		n. 黎明，拂晓",
"dazzle		vt.（强光等）使目眩，耀眼",
"deceive		v.欺骗，蒙蔽",
"decent		adj.体面的，像样的",
"decline		 vt.& vi.拒绝，谢绝",
"appeal		vt.呼吁，恳求",
"applaud		vt.&vi 鼓掌，喝彩，叫好",
"apply		 vt.申请;涂，敷",
"chorus		 n.合唱队",
"chronic		adj.（疾病）慢性的，（人）久病的",
"clarity		n.澄清，阐明",
"cling		 vi&vt.粘着",
"clumsy		adj.笨拙的",
"monitor		n.班长 ；vt.监控",
"mortgage		n.&vt 抵押（借款",
"motion		n.动，运动",
"motive		n.动机，目的",
"mount		 vt.& vi.登上， 爬上",
"cluster		n.（果实，花等的）串，束，簇; (人或物)的群，组",
"clutch		vt.紧抓，紧握",
"coherent		 adj.一致的，协调的",
"cure		vt.治愈，医治",
"cut		 vt.& vi.切，割，剪，砍，削",
"screen		 n.屏，幕，帘",
"decompose		 vt.& vi.分解，腐烂，腐败",
"dedicate		 vt.奉献，把。。。用在",
"deduce		vt.演绎，推论",
"define		vt.&vi解释，给。。。下定义",
"Deform		vt.&vi (使)变形",
"constant		 adj.经常的，不断的",
"constitute		 vt.组成，构成",
"consult		vi&vt.请教，与......商量",
"consume		vt.消费,花费",
"contact		n.&vt接触,联系,交往",
"contain		vt.包括,容纳",
"contaminate		 vt.弄脏,污染,玷污,毒害",
"calculate		 vt.& vi.计算，推算",
"call		 v. 喊，叫",
"cancel		vt. 取消，废除，删去",
"capture		vt. 俘虏，捕获",
"assume		假定，假设",
"assure		 vt.深信不疑地对......说，向......保证",
"assurance		 n.保证，把握，信心",
"astonish		 vt.使惊讶",
"attach		 vt.& vi.系，贴，连接",
"attain		 vt.& vi达到，获得",
"attend		vi&vt.出席，参加（会议等",
"attendance		 n.出席，参加，出席人数，出席率",
"attentive		adj.注意的，专心的",
"attribute		 vt.把归因于，把......（过错的责任等）归于",
"auxiliary		adj.辅助的",
"avail		 vt.& vi.有利于，有助于",
"average		n.平均数,平均",
"avert		 挡开，防止，避免",
"ban		vt.&n.（以官方明令）禁止，取缔",
"bang		 n. （突发的）猛击; 猛撞; 巨响; 爆炸声",
"cast		vt.投，扔，抛，撒，掷",
"contempt		n.轻视,轻蔑",
"contest		n.&vt&vi.竞赛,比赛,竞争",
"contract		n.合同,契约",
"contradict		vt&vi.反驳,同….相矛盾,同….相抵触",
"defy		vt.&n.公然违抗，反抗",
"degenerate		n.衰退，堕落，变坏",
"deliberate		adj.慎重的，深思熟虑的",
"denote		 vt.表示，是。。。的标志，意思是",
"Correspond		 vi.相符合相称",
"Correspondent		n.通信者,通讯员,记者",
"Corresponding		adj.符合的,一致的",
"compact		 vt.& vi. 紧密的，坚实的",
"compare		 vt.& vi.比较，对照",
"compatible		adj. 能和睦相处的，合的来的",
"detain		vt.留住，担搁",
"detect		vt.（当场）发现（某人在干坏事",
"deteriorate		vt.&vi（使）恶化,(使)变坏,(使)退化",
"deviate		v.背离，偏离",
"devote		vt.将...献给",
"compile		vt.汇编，编制",
"comply		vi.遵从，顺从，服从",
"compose		vt.组成，构成",
"compress		vt.压缩",
"comprise		vt.包含，包括",
"compromise		 n.&vi.&vt.妥协，折衷",
"confront		 vt.（使）面临，（使）遭遇",
"crucial		adj.决定性的，关键性的",
"cue		n.提示，暗号，信号",
"cultivate		vt.耕作，栽培，养殖",
"differentiate		 vt.& vi.使不同，使有差别，区分，区别",
"diffuse		vi.&vt.扩散（气体，液体等",
"disgust		vt.厌恶，恶心",
"disperse		 vt.& vi.分散，驱散，散去",
"displace		 vt.移走; 替换，移动。。。的位置",
"dispose		 vt.& vi.布置，整理",
"disregard		vt.不理会，不顾",
"distinct		adj.有区别的，不同的",
"distort		vt.&vi扭歪，扭曲：a face distorted by (或",
"distract		vt.使转向",
"distribute		 vt.分配，分发",
"eliminate		vt.排除,消除",
"elite		n.出类拔萃的人(或物),精华",
"eloquent		adj.雄辩的,口才流利的,有说服力的",
"embark		vi.上船(或飞机,汽车等):embark for Europe at New York harborvt.vt.使…上船或飞机",
"embody		vt.使具体化,表现",
"embrace		 vt.& vi.拥抱",
"enlighten		vt.启发,使摆脱偏见(或迷信",
"enroll		v.吸收(成员),招生",
"ensure		vt.保证,担保",
"diminish		vt.减少，降低",
"diplomat		n.外交家，外交官，圆滑的人",
"discard		vt.丢弃，抛弃",
"discern		vt.看出，觉察出",
"disclose		vt.揭露，透露，使公开",
"discharge		 vt.& vi.释放",
"discount		vt.把（价格，费用等）打折扣，削价出售",
"discriminate		 vt.& vi.区别，辨别",
"disgrace		 n.丢脸，耻辱",
"entertain		 vt.给。。。娱乐,使有兴趣",
"entitle		 vt.给。。。权利,给。。。资格",
"equivalent		 adj.相等的,相同的",
"erase		 vt.擦掉,抹掉,消除",
"erect		 adj.竖直的,垂直的,竖起的",
"erupt		  vt.(火山,喷泉等)喷发",
"essence		 n.本质,实质,要素",
"eternal		 adj.永恒的,永存的,永久的",
"evaluate		 vt.估价,评价",
"evaporate		  vt.(使)蒸发,(使)挥发",
"exaggerate		 vi.夸张,夸大,对…言过其实",
"exceed		 vt.超出,胜过",
"external		 adj.外面的,外部的",
"descend		 vi.下来，下降",
"Extract		 vt.取出,提取",
"Extravagant		 adj.奢侈的,浪费的",
"fabricate		 vt.建造,制造",
"facilitate		 vt.使变得(更)容易,使便利",
"fade		  vi.(颜色)褪去",
"faint		 adj.不清楚的,模糊的,微弱的",
"fancy		 n.想象力",
"fare		 n.车费,船费,飞机票价",
"divorce		 n.离婚，分离，脱离",
"dominate		 vt.分配，统治",
"donate		 vt.捐赠，赠送",
"doom		 n.命运，厄运，劫数",
"doze		 vi.打瞌睡，打盹儿",
"drain		 vi.慢慢排去",
"dread		 vt.怕，畏惧",
"drift		 vi.漂流，漂泊",
"dubious		 adj.引起怀疑的，不确定的",
"due		 adj.欠款的，应支付的",
"Dump		 vt.倾倒，倾卸",
"Duplicate		 adj.完全一样的，复制的",
"excess		 n.超越,超过",
"execute		 vt.实行,实施,执行,履行",
"exemplify		 vt.例示,举例证明,是…的例证(或榜样等",
"exert		 vt.用力,尽力",
"Exhaust		 vt.汲空,抽完",
"expand		 vt.扩大,扩展,膨胀",
"expel		 vt.驱逐,赶走",
"expend		 vt.花费,消费",
"expire		 vi.满期,届期,(期限)终止",
"explicit		 adj.详尽的,明确的",
"exploit		 n.英勇的或冒险的行为或事迹",
"exterior		 adj.外部的,外面的,外表的",
"durable		 adj.耐用的",
"dwell		 vi.（dwelt 或 dwelled ）（尤指作为常住居民）居住",
"economical		 adj.节约的,节俭的,经济的",
"generate		 vt.产生，发生(电、热、光、力、摩擦力等",
"genuine		 adj.真的，非人造的，名副其实的",
"gesture		 n.手势，示意动作",
"confine		 vt.限制，使局限",
"confirm		 vt.证实，肯定",
"conflict		 n.（尤指长期的）战争，战斗",
"conform		 vt.遵照，适应  confirm to(或",
"flourish		 n.茂盛,繁荣,兴旺",
"fluctuate		 vt.波动,起伏",
"flush		 vt.脸红",
"forbid		 vt.不许,禁止",
"forge		 n.锻炼",
"glance		 n.一瞥，扫视",
"glare		 n.怒视，瞪眼",
"dense		 adj.稠密的，密集的",
"deposit		 vt.存放",
"Depress		 vt.使沮丧，使消沉",
"deprive		 vt. 剥夺，使丧失",
"derive		 vt.取得，得到",
"controversy		  n.(尤之以文字形式进行的争论),辨证",
"convention		  n.(正式)会议,(定期)大会",
"convert		 vt.转变,转化",
"convey		 vt.运送,输送,传送",
"convict		  vt.(经审讯)证明…有罪,宣判…有罪",
"coordinate		 vt.调节,协调",
"cordial		 adj.热情友好的,热诚的,真心的",
"glimpse		 n.一瞥，一看",
"glitter		 vi.闪闪发亮(或发光)，光彩夺目，闪耀",
"glory		 n.光荣，荣誉",
"glow		 vi.发热，发光，发红",
"gossip		 n.流言蜚语",
"govern		 vt.统治，管理",
"grace		 vt.优美",
"graduate		 vt. (使)大学毕业",
"grant		 vt.同意，准予",
"grease		n.油脂，动物脂",
"heal		vt.&vi.治愈，愈合",
"heap		 n.(一)堆",
"hedge		 n.(矮树)树篱",
"highlight		vt.使显著，使突出",
"fracture		 vt.& vi.&n.裂缝,裂痕",
"frequent		adj.时常发生的,频繁的",
"frown		 vt.& vi.皱眉",
"frustrate		vt.挫败,阻挠,使灰心,使无效",
"fulfill		 (fulfilled, fulfilling)vt.履行,实现,完成",
"furnish		vt.供应，提供",
"fury		n.狂怒，暴怒",
"fuss		 vi.大惊小怪; 忙乱; 抱怨; vt.使烦恼，使烦忧; 使急躁; n.大惊小怪，乱忙，小题大做",
"hinder		 vt.& vi妨碍，阻止",
"hint		n.暗示",
"enforce		vt.实施,使生效",
"engage		 vt.(用契约诺言等)约束,使订婚",
"enhance		vt.提高(价格,质量,吸引力等),增加,增强",
"figure		n.数字",
"finance		n.财政,金融",
"finite		adj.有限的,有限制的",
"flare		 vt.&vi(火焰)闪耀,(摇曳不定地)燃烧",
"flash		 vt.& vi.闪光,闪烁",
"flat		adj.平坦的,扁平的",
"inaccessible		adj.达不到的",
"incline		 vt.& vi.倾斜",
"incorporate		vt.&vi.包含，吸收",
"incur		vt.招致，引起，遭受",
"modify		vi.&vt.修改，更改",
"momentary		adj.片刻的，瞬息的",
"designate		vt.指明，表明",
"desolate		adj.荒芜的，不毛的",
"despise		vt.蔑视，鄙视",
"detach		vt.拆卸",
"Diagnose		vt&vi.诊断，判断",
"dictate		vt.&vi口授，使听写",
"coincide		vi相符，相一致",
"collaborate		vi（尤指在文艺、科学等方面）合作，协作",
"collapse		vi&vt.倒坍，崩溃，瓦解",
"collide		vi碰撞，互撞",
"commemorate		vt.纪念，庆祝",
"commend		vt.表扬，称赞",
"extinct		 adj. (火等)熄灭了的",
"extinguish		vt.熄灭,扑灭",
"multiply		 vt.& vi.乘，相乘",
"muscle		n.肌肉",
"mutual		adj.相互的， 彼此的",
"narrate		vt&vi.叙述，讲述",
"negligent		 adj.疏忽的，大意的",
"indignant		adj.愤怒的，愤慨的",
"indispensable		adj.必不可少的，必需的",
"induce		vt.引诱，劝使",
"infer		 vt.&vi(根据已知事实等)推断，推定",
"ingenious		 adj.(人,头脑等)灵巧的，足智多谋的",
"instant		adj.紧急的，急迫的，立即的，即刻的",
"institute		n.学会，协会，学院，研究院",
"insulate		vt.隔音，使隔绝(以免受到影响",
"insult		vt.&n.侮辱，辱骂",
"flatter		vt.奉承,使高兴",
"Flee		vi&vt.逃走,逃掉",
"Flexible		 adj.灵活的; 柔韧的; 易弯曲的",
"fling		 vt.& vi. (用力)扔,掷,抛,丢",
"hoist		vt&vi.举起，升起，吊起",
"hold		vt.拿着，抓住",
"homogeneous		 adj.同种类的，同性质的，有相同特征的",
"horizon		地平(线",
"hospitable		 adj好客的，殷勤的，热情友好的",
"hostile		adj 敌人的，敌方的",
"withstand		vi 经受，承受",
"speculate		 vi推测，推断",
"spill		 vt溢出，溅出",
"spinvt纺		spin vt纺制",
"spit		 vt吐出",
"splash		 vt 溅泼",
"split		 vt 劈开，切开，裂开",
"spoil		 vt损坏，毁掉",
"sponsor		 n发起者，主办者，保证人，赞助者",
"spot		 n斑点，污点",
"spray		 n浪花，水花",
"sprout		vi 抽条，发芽，长出",
"spur		 n靴刺，踢马刺",
"renovate		 vt修复，整修",
"repel		 vt击退，抵制，拒绝，排斥",
"repent		 后悔，懊悔",
"replace		 vt 代替，取代，更换",
"transmit		 vt播送，发射",
"transparent		 adj透明的",
"transplant		 vt移植，移种，移居",
"treasure		 n财宝，财富",
"trend		 n倾向，趋势",
"trick		 n诡计，骗局",
"trifle		 n琐事，小事",
"trim		 adj整齐的，整洁的",
"triple		 adj三倍的，三重的，三部分的，三方的",
"triumph		 n 胜利",
"trivial		 adj琐碎的，不重要的，无价值的",
"tuck		 vt 夹入，藏入",
"tug		 vt（用力）拖或拉",
"stroke		 vt敲，打，鸣",
"tend		 vi趋向，倾向",
"tender		 adj嫩的",
"represent		 vt 代表，象征",
"reproach		 n责备，指责，斥责",
"scratch		 vt抓，刮，擦",
"shield		 n 盾，保护物，防御物",
"snob		 n势力的人，谄上欺下的人",
"soak		 vi 湿透，浸湿，浸泡",
"sobe		 adj未醉的",
"sophisticated		老于世故的",
"sore		 adj 痛的，痛苦的，痛心的",
"sow		 vt播种",
"spark		 n火花，火星",
"sparkle		 n发光，闪耀",
"tentative		 adj 试验性的，试探性的，暂时的，推测的",
"terminate		 vt停止，结束，使终止",
"terrify		 vt使害怕，使惊吓",
"testify		 vt 作证，证明",
"humble		 adj 地位(或身份)低下的，卑贱的",
"hysterical		 adj情绪异常激动的，歇斯底里的",
"identical		 adj同一的",
"identify		 vt识别，鉴别",
"idle		 adj闲散的，闲置的",
"ignite		 vt点燃，使燃烧",
"impose		vi 征(税)，加(负担，惩罚等)于",
"impulse		 vt推动，驱动",
"intact		 adj完整无缺的，未经触动的，未受损伤的",
"integrate		 vt使成一体，使合并",
"interfere		 vi 妨碍，冲突",
"intermittent		 adj 间歇的，断断续续的，周期性的",
"hazard		 n危险，危害物，危险之源",
"label		n 标签，标记，标号",
"lag		 n 走得慢，落后，滞留",
"latent		 adj潜在的，隐伏的，不易觉察的",
"leak		 n漏洞，裂缝",
"lean		 vi 斜，倾斜",
"initiate		vt 开始，发起",
"innovate		 vi革新，改革，创新",
"inquire		 vt 询问，打听",
"insert		 vt插入，嵌入",
"inspire		 vt鼓舞，激起",
"tumble		 vi 跌到，滚下",
"tune		 n曲调，曲子",
"turbulent		 adj骚乱的，动荡的，混乱的，狂暴的",
"turn		 vt 转动，旋转",
"tutor		 n家庭教师，指导教师",
"twinkle		 vt 闪烁，闪耀，闪亮",
"twist		 vt 捻，搓，绞，拧",
"whistle		 n 吹口哨，鸣笛",
"whitewash		 n粉饰",
"wholesome		 adj有益于健康的",
"wicked		 adj坏的，邪恶的，淘气的，恶作剧的",
"tease		vt戏弄，取笑",
"tedious		 adj单调乏味的，冗长的，罗嗦的",
"liable		 adj会……的，有……倾向的",
"liberal		 adj 慷慨的，大方的",
"limp		 adj软的，松沓的",
"linger		 vi逗留，徘徊",
"lubricate		 vt使润滑",
"lump		 n块，小方块",
"macroscopic		 adj肉眼可见的",
"magnet		 n 磁铁，磁铁石",
"magnify		 v 放大，扩大",
"maintain		 vt维持，保持",
"malfunction		 vi 发生功能障碍，发生障碍",
"maltreat		 n 粗暴地对待，虐待",
"manifest		 adj显然的，明了的",
"model		  n模型，原形",
"nominal		 adj 名义的，有名无实的",
"nominate		vt 提名",
"noteworthy		 adj值得注意的，显著的",
"intervene		 vi插入，介入",
"intricate		adj 错综复杂的，复杂精细的",
"invert		 vt使反向，使倒转，使颠倒",
"irrespective		 adj 不考虑的，不顾的",
"irritate		 vt 激怒，使恼怒，使烦躁",
"justify		 vt证明。。。正当或有理,正确",
"knit		 vt 编织，编结",
"greet		 vt 问候，招呼",
"grieve		 vt 使悲伤，使伤心",
"grind		 vt  (ground)磨，磨碎，碾碎",
"grip		 vt抓紧，紧握",
"gross		 adj 总的，毛的",
"guarantee		 n保证，保证书，保单",
"hail		 vt 欢呼，喝彩",
"halt		 vt (行进中的)暂停前进，中止，终止",
"hamper		 vt 妨碍，阻碍",
"handicap		 障碍，不利条件",
"haste		 n急速，急忙，仓促，草率",
"hatch		 vt 孵，孵出",
"manipulate		vt (熟练地)操作",
"mature		 adj 熟的，成熟的",
"melt		 vt 使融化，使熔化",
"mend		 vt 修理，修补",
"merit		 n 长处，优点，价值，功绩",
"migrate		 vi 移居(尤指移居国外)，迁移",
"minimum		 n最低限度，最少量，最低点",
"minor		 adj较小的，较少的，较不重要的",
"mislead		 vt 把……引错方向，把……引入歧途",
"moan		 n呻吟声，呜咽声",
"mobilize		 vt 动员",
"Mock		 vt 嘲笑，嘲弄",
"Ornament		n 装饰品，点缀品",
"orthodox		 adj正统的，正宗的",
"outline轮廓，外		outline轮廓，外形",
"overflow		 n泛滥",
"overhaul		vt 大修，全面检查，彻底革新",
"overhear		vt 偶然听到，偷听到",
"occupy		 vt占用，占有",
"occur		发生，存在，出现",
"odd的奇数的，单的，奇怪		odd的奇数的，单的，奇怪的",
"wicked		 adj坏的，邪恶的，淘气的，恶作剧的",
"wind		vi 绕，缠",
"Wire		 n金属丝，金属线",
"withdraw		抽回，收回，提取",
"withhold		vt 使停止，阻挡",
"withstand		vt 经受，承受",
"witness		 n目击者，见证人",
"offend		vt 冒犯，使生气",
"offence		 n 犯法行为，过错",
"offset		 vt补偿，抵消",
"Omit		 vt 省略，删去",
"overlap		 n 重叠，部分相同",
"overtake		 vt赶上，超过",
"overthrow		 vt推翻，打倒",
"overwhelm		vt 征服，压倒，毁坏",
"pace		 n 步，步速，步伐",
"pack		n 包，包裹",
"pad		 n垫，衬垫",
"pant		  vi 气喘，气喘吁吁地说话",
"parallel		 adj 平行的",
"patent		n专利，专利权，专利品",
"pattern		n 模范，榜样",
"periodical		 adj期刊，杂志",
"perish		vi 卒，丧生",
"perpetual		adj 永久的，永恒的，长期的",
"pool水池，游泳		pool 水池，游泳池",
"notorious		 adj臭名昭著的",
"notwithstanding		adv 虽然，尽管",
"nourish		 vt养育",
"numb		 adj麻木的，失去感觉的",
"object		 n 物体，事物",
"objective		 n目的，宗旨",
"oblige		 vt 强迫，迫使",
"obscure		 adj 晦涩的，费解的",
"nasty		 adj龌龊的，肮脏的",
"necessitate		 vt 使成为必须，需要",
"necessity		 必要（性），（迫切）需要",
"neglect		 vt忽视，忽略",
"obsolete		 adj 废弃的，淘汰的",
"obstinate		 adj  顽固的，固执的，倔强的",
"occasion		 n时刻，场合",
"opaque		 adj 不透明的",
"optimistic		 adj  乐观的，乐观主义的",
"option		 n选择权",
"orient		 n东方，东方国家",
"origin		 n 起源，由来",
"portable		 adj 便于携带的，手提式的，轻便的",
"pose姿势，样		pose 姿势，样子",
"postpone		 vt 延迟，延缓，延期",
"potential		 adj 潜在的，可能的",
"rally		 vt集合，团结",
"paralyze		 vt 使瘫痪，使麻痹",
"partial		 adj 偏向一方的，偏袒的，偏爱的",
"participate		 vt 参与，参加",
"particularpə'tɪkjʊlə]adj特殊的，特别		 adj特殊的，特别的",
"pat		 vt    (用掌或扁平物)轻拍，轻打",
"patch		 n 补钉，补片",
"hip		 n.臀部，髋；屋脊",
"pave		 vt铺路，铺砌，铺筑",
"hum		  v.哼曲子；发嗡嗡声；忙碌n.嗡嗡声，嘈杂声",
"profound		 adj很深的",
"prohibit		 vt禁止",
"prolong		 vt延长，拉长，拖延",
"prominent		 adj突起的，凸出的",
"prompt		adj 敏捷的，迅速的",
"pour		 vt倒，注，灌，倾泻，涌流",
"preach		 vi讲道，布道",
"preside		 vt 主持，主管",
"press		 vt按，挤，压",
"presume		 vt推测，假定，假设",
"prevail		 vi流行，盛行",
"prey		 n被捕食的动物，捕获物",
"prick		 n 一刺，一扎",
"proceed		 vi（尤指停顿或打断后）继续进行",
"proclaim		 vt宣告，宣布，声明",
"propose		 vt提议，建议",
"prosper		 vi 兴旺，繁荣，昌盛，成功",
"provoke		 挑动，激起，导致",
"radiate		 (光，热等）辐射，发射",
"radical		 根本的，基本的",
"humiliate		 v.使羞辱，使丢脸[同",
"lapse		 n.失误；(时间的)流逝 vi.逐渐下降；终止",
"laptop		 n.小型计算机",
"perplex		 vt 使困惑，使茫然",
"persecute		 vt 虐待，残害，迫害",
"perspective		 n透视画法，透视图",
"pessimistic		 adj 悲观的",
"petition		 n 请愿，请愿书",
"piercepɪəs]vt刺入，刺穿，穿		 vt 刺入，刺穿，穿透",
"pilot		 n 飞行员，驾驶员",
"pin		 n 大头针，别针",
"pinch		 vt 捏，拧，夹",
"plausible		 adj 论点等貌似有理的",
"plead		 vt恳求，请求",
"pledge		 n 保证，誓言，誓约",
"plot		 n 小块土地",
"plug		 n塞子，栓",
"plunge		 vt猛地投入或插入",
"pocket		 n 衣袋，口袋，袋子",
"polish		 vt 擦光，擦亮",
"poll		 n 民意测验",
"layman		 n.俗人，外行，门外汉",
"random		 adj胡乱的，任意的，随意的",
"range		 n排，行，一系列",
"rank		 n排，行，列",
"rate		 n比率，率",
"reap		 vt 收割，收获",
"rear		  n 后部，后边，背部",
"recall		vt回忆，回想",
"reciprocal		adj 相互的，交互的",
"reckon		 计算，数",
"hurl		 vt.猛投，力掷；大声叫骂",
"hurricane		 n.飓风 ；十二级风",
"hypocrisy		 n.伪善，虚伪",
"ideology		 n.意识形态，(政治或社会的)思想意识",
"infrastructure		  n.基础结构，基础设施",
"inhale		 v.吸入(气体等)，吸(烟",
"juvenile		 n.少年 a.青少年的，适合青少年的；幼稚的",
"kin		 n.家族，亲属 a.亲属关系的",
"reclaim		 vt 使改过，改造",
"recognize		 vt认出，识别",
"recollect		 v 回忆，想起",
"recommend		 vt 推荐，称赞",
"reconcile		 vt 使和解，使和好",
"recover		 vt 追回，重新得到",
"recruit		 vt 招募（新兵）招收（新成员",
"rectify		 vt纠正，改正，矫正",
"refer		 vt提到，谈到",
"refine		 vt提炼",
"pump		 n泵",
"pursue		 vt追赶，追随，追求",
"puzzle		 n难题，智力玩具，迷，迷惑",
"quality		 n 质量，品级",
"quantity		 n 数量，量",
"quench		 vt 消除，平息，压制，扑灭",
"queue		 n一队人，一行列车",
"quit		 vt停止，放弃",
"peculiar		 adj 奇怪的，古怪的",
"peel		 v 削皮，剥皮",
"penetrate		 vt 穿透，渗入",
"perceive		 vt 感知，感觉，觉察",
"perfect完美的，理想		perfect 完美的，理想的",
"perform		 vt 做，执行，完成",
"Perfume		 n 香水，香料，香气",
"hop		 v.人单足跳;跳上(车等)n.蹦跳;短程飞行",
"hound		 n.猎狗；卑鄙的人 vt.用猎狗追，追逐",
"housingn.住房，住房供给；(外、阀)壳，防护		housing n.住房，住房供给；(外、阀)壳，防护罩",
"hover		 vi. 盘旋；徘徊",
"howl		 n.怒吼，嗥叫 vi.(风等)怒吼，咆哮",
"huddle		  vi.挤作一团；蜷缩vt.聚集n.挤在一起的人",
"quiver		 vi 颤抖，抖动",
"quote		 vt引用，引述，援引",
"rack		 n  架子，支架，搁架",
"reform		 vt 改革，改良",
"refresh		 vt 使恢复活力，使振作精神",
"refute		 vt驳斥，驳倒",
"regenerate		 vt使恢复，使复兴，再生",
"regulate		 vt管理，控制，为……制订规章",
"reign		 vt 为王，统治",
"reinforce		 vt 增援，加强",
"rejoice		 vt 使感到高兴，使充满喜悦",
"relate		 vt 讲述，叙述",
"relay		 vt接力传送，传递",
"release		 vt 排放，释出",
"relevant		 adj 有关的，切题的",
"relieve		 vt缓解，减轻，解除",
"rescue		 vt 营救，救援，搭救",
"resent		 vt 怨恨",
"reserve		 vt 保留，储备",
"resign		 vt辞职，引退",
"resolve		 vt 决定，打定注意要",
"Resort		 vi 求助，凭借，诉诸",
"reverse		 adj 相反的，颠倒的，倒退的",
"revise		 vi 修订，校订",
"reviveɪ'vaɪv]vi苏醒，复		 vi 苏醒，复苏",
"ridiculous		 adj 可笑的，荒唐的，荒谬的",
"rigid		 adj刚性的，坚硬的",
"ripe		 adj 成熟的，时机成熟的",
"rot		n 腐烂，腐坏，腐朽，腐败，腐化",
"roundabout		 adj 绕道的，绕圈子的，不直接的",
"scan		 vt 细看，审视",
"scare		 vt 惊吓，恐惧",
"scatter		 vt撒，撒播",
"schedule		 n时间表，进度表",
"scheme		 n计划，方案",
"scold		vi 责骂，训斥",
"scorn		 vt轻蔑，鄙视",
"scrap		 n碎片，零屑",
"scrape		 vt 刮，擦",
"remark		 vt评论，议论",
"remedy		 n 治疗，治疗法，药品",
"spectacle		 n景象，奇观，壮观，场面",
"squeeze		 vt榨，挤",
"stern		 adj严厉的，苛刻的",
"stimulate		 vt刺激，促使",
"ignore		 vt 不顾，不理，忽视",
"illuminate		 vt 照明，照亮，解释，启发，启迪",
"illustrate		  vt(用图或例子)说明，阐明",
"immerse		 vt使浸没",
"shift转移，移		shift  转移，移动",
"shrewd		 adj 机灵的，敏锐的，精明的",
"synchronize		 vt使同步，使结合，使协调",
"taboo		 n禁忌，忌讳",
"tackle		 n 用具，装备",
"transient		 adj短暂的，转瞬即逝的",
"simulate		 vt 假装，冒充",
"sketch		 n 素描，速写",
"slack		 adj 不紧的，不严的",
"slender		 adj苗条的，修长的，细长的",
"edible		 adj可以吃的,可食用的",
"elaborate		 adj精心计划(或制作)的,详尽的",
"elevate		 vt举起,提高,抬起",
"fascinate		 vt强烈的吸引,迷住,使神魂颠倒",
"emigrate		 vi移居外国(或外地区",
"emit		 vt发出,散发(光,热,电度,声音,液体,气味等),发射电子",
"endeavor		vt (为达到某一目的而)努力,尝试",
"compulsory		 adj 必须做的，义务的",
"conceal		 vt 隐藏，隐瞒，隐蔽",
"conceive		 vt 构想出，设想",
"restore		 vt恢复，修复，康复",
"restrain		 vt抑制，遏止",
"resume		 vt 重新开始，继续",
"rouse		 vt 惊起",
"row		 n 吵闹，争吵",
"rub		 vt擦，摩擦",
"rust		 n锈，铁锈",
"ruthless		 adj无情的，残忍的，冷酷的",
"sack		 n  麻袋，纸袋，塑料袋",
"sacred		 adj神圣的",
"sacrifice		 n献祭，供奉",
"salute		 vt 敬礼，祝贺",
"retain		 vt保留，保持",
"reveal		 vt 揭示，揭露",
"revengerevengevt报仇，复		revenge revenge vt报仇，复仇",
"concentrate		 vt 集中，专心",
"condemn		vt 谴责",
"condense		 vt （使）压缩，（使）凝结，使简洁",
"confer		vt 商谈，商议",
"Confess		 vt  坦白，供认，承认，忏悔",
"formulate'fɔːmjʊleɪt]vt规划(制度等),构想出(计划方法		 vt规划(制度等),构想出(计划方法等",
"gallop		 vi(马等的)飞跑，疾驰",
"gamble		 vi赌博",
"gasp		 vi 喘气，喘息",
"gear		 n齿轮，传动装置，(排)档",
"generalize		 vt 归纳，概括",
};
#define EnglishWordCount (sizeof(EnglishWord)/sizeof(char *)) 
#endif