#ifndef _ENGLISHWORD_H
#define _ENGLISHWORD_H

// 考研英语高频词汇

#include <string>
using namespace std;
const char* EnglishWord[] = {
  "rape	[reip]	 n.强奸；破坏，蹂躏 vt.强奸；破坏，蹂躏",
"rash	[ræʃ]	 a.轻率的，鲁莽的 [反]deliberate   n.皮疹",
"guideline	[ˈgaɪdlaɪn]	 n.指导方针，指导原则，准则，标准",
"gut	[ɡʌt]	  n.[pl.]胆量；内脏a.本能的vt.取出内脏",
"refund	[ˈri:fʌnd]	  n.v. 退款；赔偿",
"relish	[ˈrelɪʃ]	   n.喜好，乐趣；美味；胃口 v.爱好，喜欢",
"remnant	['remnənt]	 n.残余，剩余；残余物，残存部分",
"renaissance	[ri'neisns]	 n.[the R-]文艺复兴(时期)；新生，复兴",
"habitat	[ˈhæbɪtæt]	   n.(动物的)栖息地，(植物的)产地",
"harassment	['hærəsmənt]	 n.骚扰，扰乱；烦恼，烦乱",
"recycle	[ˌri:ˈsaɪkl]	 vt./vi.重复利用(用过的物资)，循环使用",
"redundant	[ri'dʌndənt]	 a.被解雇的；多余的，过剩的",
"refugee	[ˌrefjuˈdʒi:]	 n.(政治上的)避难者，难民",
"ritual	[ˈrɪtʃuəl]	    a.宗教仪式的，典礼的 n.仪式，典礼；惯例",
"robust	[rəu'bʌst]	a.强健的，茁壮的；有力的  [反",
"salvation	[sæl'veiʃən]	n.(尤指基督)救世，超度；拯救，解困",
"sanction	['sæŋkʃən]	v.同意(某事)，批准，认可 n.批准,国际制裁",
"repression	[rɪˈpreʃn]	 n.压抑，压制，镇压",
"sane	[seɪn]	    a.心智健全的，神志清醒的；明断的，理智的",
"sarcastic	[sɑ:'kæstik]	a.讽刺的，嘲笑的，挖苦的",
"saturate	['sætʃəreit]	vt.使湿透，浸透；使充满，使饱和",
"repertoire	['repətwɑ:]	n.全部剧目,保留剧目,全部技能",
"retention	[ri'tenʃən]	n.保留；保持；记忆(力",
"retort	[ri'tɔ:t]	n.v.报复；反击；反驳",
"boost	[bu:st]	    n.促进，激励；一抬；一推 vt.推动，增强",
"bowel	['bauəl]	n.肠；［pl.］内部，深处",
"retrieve	[rɪˈtri:v]	  vt.重新得到，取回；挽回，补救；检索",
"retrospect	['retrəspekt]	v.n.回顾，回想，追溯[反",
"revelation	[,revə'leiʃən]	n.揭示，透露，显示；被揭示的真相，新发现",
"rigorous	[ˈrɪgərəs]	 a.严格的，严厉的，严酷的(气候条件",
"riot	[ˈraɪət]	    n.暴(骚)乱；(色彩等)极度丰富vi.聚众闹事",
"rip	[rɪp]	    v.猛撕开；扯开；被撕开；裂开",
"scandal	[ˈskændl]	 n.丑事，丑闻；流言蜚语；反感，愤慨",
"scramble	['skræmbl]	vi.(快速地)爬，攀登；互相争夺，争先",
"siege	[si:dʒ]	   n.包围，围攻，围困",
"sip	[sɪp]	  v.小口地喝，抿，呷  n.一小口的量",
"sceptical/skeptical	[ˈskeptɪkl]	 a.怀疑的",
"skim	[skɪm]	   vt.撇去(液体表面)之漂浮物 vi.轻轻掠过",
"skip	[skɪp]	    vi.略过，跳过 n.跳跃 vt.故意忽略；略过",
"fridge	[frɪdʒ]	  n.(refrigerator的略语)冰箱",
"radiant	['reidiənt]	a.(面容、目光)洋溢着幸福的，明亮照耀的",
"rap	[ræp]	    vt.急敲；突然厉声说出；训斥n.急敲(声",
"thermal	['θə:məl]	热的，由热造成的",
"texture	[ˈtekstʃə(r)]	  n.(织物)质地；(材料)构造；结构；肌理",
"transcend	[trænˈsend]	 vt. 超出，超越(理性等)的范围",
"abolish	[əˈbɒlɪʃ]	   彻底废除（法律、制度、习俗等",
"prime	[praɪm]	   首要的，主要的",
"foul	[faʊl]	   a. 令人不快的；恶臭的；邪恶的 v.弄脏 n.(体育等)犯规",
"thirst	[θɜ:st]	    渴，口渴",
"trail	[treil]	痕迹，足迹",
"tramp	[træmp]	步行，跋涉",
"transfer	[trænsˈfɜ:(r)]	  转移，调动",
"fringe	[frindʒ]	 n.边缘；(窗帘)缘饰；额前垂发 vt.饰…的边",
"fume	[fju:m]	n.(usu pl.)（浓烈或难闻的）烟，气，汽",
"blur	[blə:]	   n.模糊不清的事物 vt.使模糊，使看不清楚",
"browse	[brauz]	vi.随意翻阅，浏览；(牛、羊等)吃草",
"primitive	['primitiv]	原始的，上古的，早期的",
"prior	['praiə]	在先的，在前的",
"privilege	[ˈprɪvəlɪdʒ]	 n 特权，优惠，特免",
"probe	[prəʊb]	 vt .  探索，探查，调查",
"verify	[ˈverɪfaɪ]	 vt.   证明",
"vertical	[ˈvɜ:tɪkl]	 adj. 垂直的，立式的",
"veto	['vi:təu ]	 n. 否决，否决权，否决权的行使",
"absolute	[ˈæbsəlu:t]	 adj  纯粹的，完全的",
"verge	[vɜ:dʒ]	 n 边，边缘，边沿",
"accustom	[əˈkʌstəm]	  vt. 使习惯",
"acquaint	[ə'kweint]	 vt. 使认识，使了解",
"trash	[træʃ]	 n.垃圾；拙劣的作品；渣滓，败类vt.捣毁",
"toxic	[ˈtɒksɪk]	 adj.有毒的，因中毒引起的",
"amaze	[əˈmeɪz]	 vt. 使惊愕，使惊异",
"breach	[bri:tʃ]	 n.违反，不履行；破裂 vt.冲破，攻破",
"briefcase	[ˈbri:fkeɪs]	 n.手提箱，公事皮包",
"ambiguous	[æmˈbɪgjuəs]	 adj.含糊不清的，模棱两可的",
"ozone	[ˈəʊzəʊn]	 n. 臭氧；清新的空气",
"script	[skrɪpt]	 n.剧本(原稿)；手稿，原稿；笔迹，手迹",
"scrutiny	[ˈskru:təni]	 n.周密的调查；仔细看；监视；选票复查",
"sculpture	[ˈskʌlptʃə(r)]	 n.雕刻(术)，雕塑(术)；雕刻作品",
"pact	[pækt]	 n.合同，条约，公约",
"trace	[treɪs]	 n. 痕迹，踪迹",
"track	[træk]	 n.足迹，踪迹",
"tragedy	[ˈtrædʒədi]	 n. 悲剧",
"paperback	[ˈpeɪpəbæk]	 n.平装本，简装本",
"tame	[teɪm]	 adj.驯化的，驯服的，温顺的",
"tan	[tæn]	 n.棕黄色，黄褐色",
"tax	[tæks]	 n.税（款",
"abrupt	[əˈbrʌpt]	adj.  突然的，意外的",
"acute	[əˈkju:t]	 adj.尖锐的，敏锐的",
"versatile	[ˈvɜ:sətaɪl]	 adj. 多才多艺的",
"versus	[ˈvɜ:səs]	 prep.(介词)诉讼，竞赛等中以…为对手",
"blunt	[blʌnt]	 adj.钝的",
"Blush	[blʌʃ]	 （因害羞、激动、窘困）脸红",
"abide	[əˈbaɪd]	 vt.遵循（…by）；容忍",
"delight	[dɪˈlaɪt]	 n. 高兴，快乐",
"deliver	[dɪˈlɪvə(r)]	 vi. 投递，传送，运输",
"demonstrate	[ˈdemənstreɪt]	 vt.论证，证明",
"accelerate	[əkˈseləreɪt]	 vt. 加速，增速",
"thread	[θred]	 n.线，线状物",
"thrill	[θrɪl]	 vt.使非常兴奋，使非常激动",
"thrive	[θraɪv]	 vi.兴旺发达，繁荣",
"abuse	[əˈbju:s]	n. vt.  滥用",
"stream	[stri:m]	 n. 小河，溪流",
"stress	[stres]	n.压力，紧张",
"stretch	[stretʃ]	 v. 伸直，伸长",
"stride	[straɪd]	 vt.& vi. 阔步前进，大踏步走",
"temper	[ˈtempə(r)]	 n. 心情，脾气",
"tempt	[tempt]	 vt.  引诱，诱惑",
"strain	[streɪn]	 vt.& vi 拉紧，绷紧",
"strap	[stræp]	 n. 带，皮带",
"strike	[straɪk]	 vi.打击，撞",
"string	[strɪŋ]	 n.细绳，线，带",
"strip	[strɪp]	 vi.&vt剥去，除去",
"access	[ˈækses]	 n.入口，出口; 接近，进入;接近（或进入）的机会",
"tip	[tɪp]	 末端，尖端",
"toast	[təʊst]	 n.干杯;烤面包，吐司",
"token	[ˈtəʊkən]	 n.&vt.表示，标志，象征",
"torture	[ˈtɔ:tʃə(r)]	 n.&vt拷打，拷问",
"accommodate	[əˈkɒmədeɪt]	 vt.使适应，使符合一致",
"unfold	[ʌnˈfəʊld]	 vt.& vi. 展开，打开",
"uniform	[ˈju:nɪfɔ:m]	 n.制服；adj.不变的，相同的，均匀，统一的",
"unify	[ˈju:nɪfaɪ]	 vt.使成一体，统",
"adhere	[ədˈhɪə(r)]	 vi&vt  黏附，附着",
"adjacent	[əˈdʒeɪsnt]	adj.  临近的，毗邻的",
"adjoin	[əˈdʒɔɪn]	 vt.& vi.  贴近，与...毗邻",
"thrust	[θrʌst]	 vt.& vi推，刺，戳，插，挤",
"update	[ˌʌpˈdeɪt]	 vt. 更新，使现代化",
"upgrade	[ˌʌpˈgreɪd]	 vt. 提高，使升级，改善",
"uphold	[ʌpˈhəʊld]	vt. 举起，高举",
"upright	[ˈʌpraɪt]	 adj. 挺直的，垂直的",
"tick	[tɪk]	 n.（钟声等发出的）滴答声",
"tilt	[tɪlt]	vt&vi.使倾斜，使倾倒",
"toss	[tɒs]	 vt.& vi. 扔，抛，掷",
"tough	[tʌf]	adj. 坚韧的，牢固的",
"tow	[təʊ]	vt.拖，拉，牵引",
"abstract	[ˈæbstrækt]	 adj. 抽象的",
"absurd	[əbˈsɜ:d]	adj. 荒谬的，荒唐的",
"uproar	[ˈʌprɔ:(r)]	n. 骚乱，骚动",
"utilize	[ˈju:təlaɪz]	vt.利用",
"utter	[ˈʌtə(r)]	vt. 发出（声音等），说，吐露",
"vacant	[ˈveɪkənt]	 adj. 未被占用的",
"vague	[veɪg]	adj. 含糊的，不明确的，模糊的",
"slip	[slɪp]	 vi&vt. 滑倒，滑落，滑行",
"slit	[slɪt]	vt. 切开，撕开",
"slope	[sləʊp]	vi. 倾斜，有坡度",
"impact	[ˈɪmpækt]	 n. 冲击，撞击 vt.挤入，压紧; 撞击; 对…产生影响",
"impair	[ɪmˈpeə(r)]	 vt.削弱，减少",
"impartial	[ɪmˈpɑ:ʃl]	adj. 公正的，无偏见的",
"implement	[ˈɪmplɪment]	n.工具，器具，用具",
"sly	[slaɪ]	 adj.狡猾的，偷偷的",
"smash	[smæʃ]	 vt. 打碎，打破，摧毁",
"snatch	[snætʃ]	 vt. 夺得，一把抓住",
"immune	[ɪˈmju:n]	 adj.免除的，豁免的",
"sting	[stɪŋ]	 vt.&vi刺，螫，叮",
"stir	[stɜ:(r)]	 vt.& vi.使微动，移动",
"stitch	[stɪtʃ]	 n.一针，针脚",
"sue	[su:]	 vt.& vi控告，起诉",
"summary	[ˈsʌməri]	 n. 总结，概要",
"superb	[su:ˈpɜ:b]	 adj. 极好的，一流的，杰出的",
"superficial	[ˌsu:pəˈfɪʃl]	adj.表面的",
"superfluous	[su:ˈpɜ:fluəs]	adj.过多的，剩余的，多余的",
"ventilate	[ˈventɪleɪt]	 vt.使通风，使空气流通",
"venture	[ˈventʃə(r)]	n.冒险，冒险行动，投机行动",
"uncover	[ʌnˈkʌvə(r)]	 vt. 揭开，揭露",
"supervise	[ˈsu:pəvaɪz]	 vt.& vi 监督，管理，指导",
"vanish	[ˈvænɪʃ]	 vi.突然消失，逐渐消散",
"veil	[veɪl]	 n. 面纱，面罩",
"underestimate	[ˌʌndərˈestɪmeɪt]	 低估",
"reassure	[ˌri:əˈʃʊə(r)]	 v.使安心，使放心；使消除疑虑",
"recede	[rɪˈsi:d]	 v.退去；缩进；收回，撤回 [反",
"recipient	[rɪˈsɪpiənt]	 n.a person who receives sth  收到者",
"reckless	[ˈrekləs]	 a.不注意的,大意的,卤莽的,不顾后果的",
"rectangle	[ˈrektæŋgl]	 n.[数]矩形, 长方形",
"recur	[rɪˈkɜ:(r)]	 v.(尤指不好的事)一再发生；重现",
"portray	[pɔ:ˈtreɪ]	 v.描写，描述；画(人物、景象等",
"prone	[prəʊn]	 a.(to)易于…的，很可能…的；俯卧的",
"prophet	[ˈprɒfɪt]	 n.预言家；先知；提倡者",
"undergo	[ˌʌndəˈgəʊ]	vt.经历，遭受，忍受",
"underlie	[ˌʌndəˈlaɪ]	 vt. 位于……之下",
"undermine	[ˌʌndəˈmaɪn]	 v. 在……下挖",
"undertake	[ˌʌndəˈteɪk]	 vt. 着手做， 从事",
"undesirable	[ˌʌndɪˈzaɪərəbl]	adj. 不合意的，不受欢迎的",
"uneasy	[ʌnˈi:zi]	adj. 心神不宁的，不安宁的",
"accord	[əˈkɔ:d]	 vt. 使符合，相一致",
"account	[əˈkaʊnt]	n.记述，叙述",
"address	[əˈdres]	 n.地址;  演说",
"ultimate	[ˈʌltɪmət]	 adj.最后的，最终的",
"unanimous	[juˈnænɪməs]	adj.全体一致的，一致同意的",
"virtue	[ˈvɜ:tʃu:]	 美德，德行",
"visible	[ˈvɪzəbl]	adj. 看得见的，可见的",
"vision	[ˈvɪʒn]	n.视力，视觉",
"substitute	[ˈsʌbstɪtju:t]	 n.代替者，代替物",
"subtle	[ˈsʌtl]	adj.微妙的，巧妙的",
"subtract	[səbˈtrækt]	 vt.减，减去",
"succession	[səkˈseʃn]	n.连续，一系列",
"suck	[sʌk]	 vt. 吸",
"vital	[ˈvaɪtl]	 adj.维持生命所必需的;有生命力的",
"vivid	[ˈvɪvɪd]	adj.鲜艳的",
"void	[vɔɪd]	 adj.空的",
"wedge	[wedʒ]	n.楔子，三角木",
"weed	[wi:d]	n.杂草，野草",
"weep	[wi:p]	 vt.& vi.（通常因悲伤）哭泣，流泪",
"weigh	[weɪ]	 vt.称……重量，称",
"Xerox	[ˈzɪərɒks]	n.静电复印（法），静电复印件，静电复印机",
"yield	[ji:ld]	vt.生产，产生，带来",
"zeal	[zi:l]	 n.热心，热忱，热情",
"vicious	[ˈvɪʃəs]	adj.邪恶的，恶毒的，凶残的",
"volunteer	[ˌvɒlənˈtɪə(r)]	n.志愿者，自愿参加者",
"Zigzag	[ˈzɪgzæg]	adj.之字形的，弯曲的",
"Wander	[ˈwɒndə(r)]	vt.&vi漫步，徘徊",
"ward	[wɔ:d]	n. 病房",
"warrant	[ˈwɒrənt]	n.授权，批准，正当理由，根据",
"waterproof	[ˈwɔ:təpru:f]	adj. 不透水的，防水的",
"whisper	[ˈwɪspə(r)]	 vt.低语，耳语，轻声说",
"audit	[ˈɔ:dɪt]	 v.审计；查帐；核对；旁听",
"vibrate	[vaɪˈbreɪt]	 vt.& vi.使震动，使摆动",
"weld	[weld]	 vt.& vi.焊接，煅接",
"whirl	[wɜ:l]	vi.&vt旋转，急转",
"audio	[ˈɔ:diəʊ]	 n./a.音频(响)(的)；声音(的)，听觉(的",
"auditorium	[ˌɔ:dɪˈtɔ:riəm]	 n.观众席，听众席；会堂，礼堂",
"stab	[stæb]	 vt.&n.刺，戳，猛的一击，突发的一阵",
"stack	[stæk]	n.整齐的一叠",
"stain	[steɪn]	vt&vi玷污，污染",
"stale	[steɪl]	adj. 食品等不新鲜的，走味的",
"stall	[stɔ:l]	 n.小隔间;牛舍",
"startle	[ˈstɑ:tl]	vt.惊吓，使吃惊",
"starve	[stɑ:v]	 vi.&vt.使挨饿，饿死",
"addict	[ˈædɪkt]	 v.使沉溺；使上瘾 n.沉溺于不良嗜好的人",
"advent	[ˈædvent]	 n.(重要事件等的)到来，来临",
"affluent	[ˈæfluənt]	 a. 富裕的，富足的",
"bait	[beɪt]	 n.饵，引诱物 vt.用饵引诱；招惹，捉弄",
"balcony	[ˈbælkəni]	 n.阳台；(电影院等的)楼厅，楼座",
"ballet	[ˈbæleɪ]	 n.芭蕾舞，芭蕾舞剧；芭蕾舞团",
"stock	[stɒk]	 n.原料，备料，库存，现货",
"stoop	[stu:p]	 vt.& vi.&n. 俯身，弯腰",
"statistics	[stə'tɪstɪks]	 n.统计，统计资料",
"steer	[stɪə(r)]	 vt.& vi.掌舵，驾驶",
"authentic	[ɔ:ˈθentɪk]	 a.真的，真正的；可靠的，可信的，有根据的",
"awe	[ɔ:]	 n.敬畏，惊惧vt.使敬畏，使惊惧",
"bizarre	[bɪˈzɑ:(r)]	 adj.异乎寻常的，稀奇古怪的",
"stubborn	[ˈstʌbən]	adj.顽固的，倔强的",
"stuff	[stʌf]	n.原料，材料，物品，东西",
"subject	[ˈsʌbdʒɪkt]	n.题目，主题",
"submerge	[səbˈmɜ:dʒ]	 vt.& vi.浸没，淹没，湮没",
"submit	[səbˈmɪt]	vt.屈服，服从，投降",
"anguish	[ˈæŋgwɪʃ]	 n.(尤指心灵上的)极度痛苦，烦恼",
"antique	[ænˈti:k]	 a.古式的，过时的　n.有价值的古物，古董票",
"Barbecue	[ˈbɑ:bɪkju:]	 n.烤肉用的台架；烤肉野餐 vt.在台架上烤肉",
"appall	[ə'pɔ:l]	 v.使胆寒,使惊骇",
"wrap	[ræp]	vt.包，裹",
"wreck	[rek]	n.失事，遇难",
"wrench	[rentʃ]	n.扳手",
"ballot	[ˈbælət]	 n.(不记名)投票；投票总数；投票权 vi.投",
"barren	[ˈbærən]	 a.贫瘠的；不育的；(植物)不结果的；无用的",
"belly	[ˈbeli]	 n.肚子，腹部；(像肚子一样)鼓起的部分，膛",
"benign	[bɪˈnaɪn]	 a.(病)良性的,(气候)良好的,仁慈的,和蔼的",
"beverage	[ˈbevərɪdʒ]	 n.(水，酒等之外的)饮料",
"bin	[bɪn]	 n.(贮藏食物等用的)箱子",
"wrinkle	[ˈrɪŋkl]	n.皱，皱纹",
"write	[raɪt]	写，写字，写信，写作",
"album	[ˈælbəm]	 n. 唱片;集邮册,相册",
"storm	[stɔ:m]	n.风暴，暴风雨，暴风雪",
"straightforward	[ˌstreɪtˈfɔ:wəd]	adj.一直向前的，直接的",
"subordinate	[səˈbɔ:dɪnət]	adj.下级的",
"substance	[ˈsʌbstəns]	n.物质，实质",
"air-conditioning	['eərkənd'ɪʃnɪŋ]	 n.空调设备，空调系统",
"stationary	[ˈsteɪʃənri]	adj.固定的，静止的，非流动的",
"amiable	[ˈeɪmiəbl]	  a.和蔼可亲的，友善的，亲切的",
"amid	[əˈmɪd]	 prep.在…中间，在…之中，被…围绕",
"auction	[ˈɔ:kʃn]	 n.／vt.拍卖",
"endow	[ɪnˈdaʊ]	 vt.资助，捐赠；(with)给予，赋予",
"escalate	[ˈeskəleɪt]	 v.(使)逐步增长(或发展)，(使)逐步升级",
"escort	[ˈeskɔ:t]	 vt.护送(卫)；陪同 n.警卫，护送者；仪仗兵",
"evade	[ɪˈveɪd]	 vt.逃避，回避；避开，躲避",
"arrogant	[ˈærəgənt]	 a.傲慢的，自大的",
"artery	[ˈɑ:təri]	 n.动脉；干线，要道",
"blueprint	[ˈblu:prɪnt]	 n.蓝图，设计图，计划 vt.制成蓝图，计划",
"ego	[ˈi:gəʊ]	 n.自我，自负，利已主义；(心理学)自我意识",
"eligible	[ˈelɪdʒəbl]	 a.有条件被选中的；(尤指婚姻等)合适(意)的",
"aspire	[əˈspaɪə(r)]	 vi.(to，after)渴望，追求，有志于",
"assassinate	[əˈsæsɪneɪt]	 vt.暗杀，行刺；中伤",
"waken	[ˈweɪkən]	vi&vt.醒来，睡醒",
"virtual	[ˈvɜ:tʃuəl]	adj.实际上的，事实上的",
"weary	[ˈwɪəri]	adj.疲倦的，疲劳的",
"vigor	['vɪgə]	n.体力，精力，活力",
"violate	[ˈvaɪəleɪt]	 vt.违反，违背",
"zone	[zəʊn]	n.地带，分布带",
"abdomen	[ˈæbdəmən]	 n.腹，下腹(胸部到腿部的部分",
"abound	[əˈbaʊnd]	 vi.大量存在；(in，with)充满，富于",
"acclaim	[əˈkleɪm]	 v.向…欢呼，公认 n.欢呼，喝彩，称赞",
"accountant	[əˈkaʊntənt]	 n.会计人员，会计师",
"aisle	[aɪl]	 n.(教堂、教室、戏院等里的)过道，通道",
"supplement	[ˈsʌplɪmənt]	n.增补，补充",
"Suppress	[səˈpres]	 vt.压制，镇压",
"Supreme	[su:ˈpri:m]	adj.最高的，至上的",
"Surpass	[səˈpɑ:s]	vt.超过，优于，强于，胜过",
"Surplus	[ˈsɜ:pləs]	n.过剩，剩余",
"Survey	[ˈsɜ:veɪ]	vt.调查",
"asset	[ˈæset]	 n.(pl.)资产(产)；有用的资源；优点，益处",
"blackmail	[ˈblækmeɪl]	 n.讹诈，敲诈，勒索；胁迫，恫吓",
"blade	[bleɪd]	 n. 刀刃，刀片；桨叶，桨片；草叶，叶片",
"blouse	[blaʊz]	 n.女衬衣，短上衣，宽阔的罩衫",
"vain	[veɪn]	adj.徒劳的，无效的",
"valid	[ˈvælɪd]	adj.有根据的",
"value	[ˈvælju:]	n.价值",
"foster	[ˈfɒstə(r)]	 vt. 照管；培养；促进",
"bruise	[bru:z]	 n.青肿，挫伤；伤痕vt.打青；挫伤",
"bully	[ˈbʊli]	 n.恃强欺弱者，小流氓 vt.威胁，欺侮",
"bureaucracy	[bjʊəˈrɒkrəsi]	 n.官僚主义，官僚机构；(非民选的)委任官员",
"burglar	[ˈbɜ:glə(r)]	 n.(入室行窃的)盗贼",
"cape	[keɪp]	 n.海角，岬；披肩，短披风",
"carbohydrate	[ˌkɑ:bəʊˈhaɪdreɪt]	 n.碳水化合物; 糖类；(plural)淀粉质或糖类",
"celebrity	[səˈlebrəti]	 n.名人，名流；著名，名声，名望",
"Christ	[kraɪst]	 n.基督，救世主，耶稣",
"clergy	[ˈklɜ:dʒi]	 n.[总称]牧师，神职人员",
"coalition	[ˌkəʊəˈlɪʃn]	 n.结合体，同盟；结合，联合",
"costume	[ˈkɒstju:m]	 n. 戏装；泳装；服装",
"cosy/cozy	['kəʊzɪ]	 / ['kəʊzɪ] a.暖和舒服的；舒适的 [反",
"credentials	[krəˈdenʃlz]	 n.(个人能力及信用的)证明书，证件",
"glamour	[ˈglæmə(r)]	 n.魔力，魅力 vt.迷住",
"strenuous	[ˈstrenjuəs]	 a.费力的，艰辛的；奋发的，努力的",
"ebb	[eb]	 vi.衰退，减退,（指潮水）退; n.处于低潮，处于衰退状态",
"eccentric	[ɪkˈsentrɪk]	 a.古怪的，怪癖的，异乎寻常的n.古怪的人",
"futile	[ˈfju:taɪl]	 a.无效的，无用的，无希望的",
"gender	[ˈdʒendə(r)]	 n.(生理上的)性；(名词、代词等的)性",
"strife	[straɪf]	 n.争吵；冲突，斗争；竞争",
"stroll	[strəʊl]	 n.&v.漫步；散步；游荡",
"gorgeous	[ˈgɔ:dʒəs]	 a.华丽的；灿烂的；美丽的；宜人的；棒的",
"graphic	[ˈgræfɪk]	 a.生动的，形象的；绘画的，文字的，图表的",
"medieval	[ˌmediˈi:vl]	 a. 中世纪的",
"excel	[ɪkˈsel]	 vi.(at，in)突出，擅长vt.胜过，优于",
"excerpt	[ˈeksɜ:pt]	 n.摘录，节录 vt.摘，引用",
"layoff	['leɪɔ:f]	 n.临时解雇；关闭；停歇",
"lottery	[ˈlɒtəri]	 n.抽彩；碰运气的事，难于算计的事",
"majesty	[ˈmædʒəsti]	 n. stately [ˈsteɪtli], grand appearance [grænd]; splendor ['splendə]雄伟，壮丽，庄严",
"manoeuvre	[məˈnu:və(r)]	 /maneuver   [mə'nu:və] vi.熟练地进入",
"exile	[ˈeksaɪl]	 n.流放；被流放者 vt.流放，放逐，把…充军",
"fairy	[ˈfeəri]	 adj.幻想中的，虚构的",
"feat	[fi:t]	 n.功绩，伟业，技艺",
"federation	[ˌfedəˈreɪʃn]	 n.联合会；结盟，联合",
"fore	[fɔ:(r)]	 ad.在前面 a.先前的；在前部的 n.前部",
"solitary	[ˈsɒlətri]	 a.(好)孤独的；偏僻的；单一的，唯一的",
"solo	[ˈsəʊləʊ]	 n.独奏 a. ad.单独的(地)；独唱的(地",
"spiral	[ˈspaɪrəl]	 a.螺旋形的 n.螺旋，螺线 v.螺旋上升；盘旋",
"spouse	[spaʊs]	 n. a  wife or husband 配偶",
"stagger	[ˈstægə(r)]	 vi.摇晃着移动;蹒跚 n.摇晃不稳的动作;蹒跚",
"stalk	[stɔ:k]	 n.茎，梗vt.悄悄地跟踪vi.高视阔步地走",
"staple	[ˈsteɪpl]	 n.主要产品；名产；纤维；主要成分，主食",
"statute	[ˈstætʃu:t]	 n.成文法，法令，法规；章程，规则，条例",
"steak	[steɪk]	 n.牛排；大块肉(或鱼)片",
"suffice	[səˈfaɪs]	 v.足够，(食物)满足",
"suite	[swi:t]	 n.套间；一套家具；套，组，系列",
"summit	[ˈsʌmɪt]	 n.顶，最高点；颠峰，高峰；最高级会议",
"superstition	[ˌsu:pəˈstɪʃn]	 n.迷信，迷信的观念习俗",
"oxide	[ˈɒksaɪd]	 n. 氧化物",
"stereotype	[ˈsteriətaɪp]	 n.陈规，老套，模式化 vt.使定型，使模式化",
"formidable	[ˈfɔ:mɪdəbl]	 a. difficult to defeat 失败[dɪˈfi:t] or deal with 难对付的；可怕的",
"meditate	[ˈmedɪteɪt]	 v.认真思考，沉思；计划，考虑",
"momentum	[məˈmentəm]	 n. 动量；动力；势头",
"monarch	[ˈmɒnək]	 n.帝王，君主，最高统治者",
"motivate	[ˈməʊtɪveɪt]	 vt.促动；激励，鼓励，作为…的动机",
"nightmare	[ˈnaɪtmeə(r)]	 n.恶梦；可怕的事物，无法摆脱的恐惧",
"optimum	[ˈɒptɪməm]	 a.最适宜的 n.(生长繁殖的)最佳条件",
"option	[ˈɒpʃn]	 n.选择(权)；可选择的事物(或人)，选课",
"overturn	[ˌəʊvəˈtɜ:n]	 n. 推翻",
"stun	[stʌn]	 vt.使…失去知觉；使目瞪口呆，使吃惊",
"subsidy	[ˈsʌbsədi]	 n.补助金；津贴费",
"grim	[grɪm]	 a.严酷的，令人害怕的；不愉快的，讨厌的",
"grin	[grɪn]	 vi. 露齿笑n.咧嘴笑",
"slaughter	[ˈslɔ:tə(r)]	 n.屠杀，屠宰 vt.屠杀，宰杀",
"slot	[slɒt ]	n.狭缝；空位vt.放入狭缝中；把…纳入",
"sneak	[sni:k]	 vi.偷偷地走，溜vt.偷偷地做(或拿、吃",
"sneeze	[sni:z]	 vi.打喷嚏，发喷嚏声n.喷嚏",
"agitate	[ˈædʒɪteɪt]	 vi&vt.搅动（液体等",
"grope	[ˈgru:vi]	 vi.暗中摸，摸索；探索，搜寻vt.摸索",
"heave	[hi:v]	 v.(用力)举，提，拉；扔；拖；呕吐n.举起",
"herb	[hɜ:b]	 n.药草，(调味用的)香草，草本植物",
"hierarchy	[ˈhaɪərɑ:ki]	 n.等级制度；统治集团，领导层",
"hike	[haɪk]	  n.徒步旅行；增加vi.徒步旅行vt.提高",
"passerby	['pɑ:sə'baɪ]	 n.过路人，路人",
"pilgrim	[ˈpɪlgrɪm]	 n.最初的移民(P大写，指1620由欧洲移居美国的清教徒",
"plea	[pli:]	 n.(法律)抗辩；请求，恳求，托词，口实",
"skull	[skʌl]	 n.头盖骨，颅骨",
"alarm	[əˈlɑ:m]	 n.惊恐，忧虑",
"sort	[sɔ:t]	n. 种类，类别",
"sound	[saʊnd]	 n.声音，声响; adj.健康的，健全的，完好的",
"sour	[ˈsaʊə(r)]	adj.酸的，酸味的",
"alert	[əˈlɜ:t]	adj.警惕的，留神的",
"alien	[ˈeɪliən]	 n.外国人; 外侨;外国的",
"allege	[əˈledʒ]	 断言，宣称",
"temperament	[ˈtemprəmənt]	 n.气质，性格，性情；资质",
"tropic	[ˈtrɒpɪk]	 n.回归线；[the T-s]热带地区",
"tumour/tumor	[ˈtju:mə(r)]	/ ['tju:mə]  n.(肿)瘤，肿块",
"amateur	[ˈæmətə(r)]	 n.（艺术，科学等的）业余爱好者",
"allocate	[ˈæləkeɪt]	 vt.分配，分派，把...拨给",
"sniff	[snɪf]	 vi.嗅…味道；抽鼻涕；对嗤之以鼻，蔑视",
"soar	[sɔ:(r)]	 vi.(指鸟等)高飞，翱翔；飞涨；高耸",
"sociable	[ˈsəʊʃəbl]	 a.好交际的，友好的，合群的",
"solidarity	[ˌsɒlɪˈdærəti]	 n.团结；休戚相关",
"surge	[sɜ:dʒ]	 vi.(如浪潮般)汹涌；奔腾 n.(感情等的)洋溢",
"susceptible	[səˈseptəbl]	 a.过敏的，敏感的；易动感情的，易受感动的",
"tangle	[ˈtæŋgl]	 n.纠缠；缠结；混乱 v.(使)缠绕；变乱",
"ambition	[æmˈbɪʃn]	n.（对名利等的）强烈欲望，野心",
"amend	[əˈmend]	 vt.& vi.修改，修订",
"administrate	[əd'mɪnɪstreɪt]	v.掌管，料理...的事务",
"adolescent	[ˌædəˈlesnt]	n.（尤指16岁以下的）青少年",
"advance	[ədˈvɑ:ns]	 vt.（使）前进;使向前移动",
"sector	[ˈsektə(r)]	 n.部门，部分；防御地段，防区；扇形",
"seemingly	[ˈsi:mɪŋli]	 ad. in appearance; apparently 表面上的，看起来的",
"alternate	[ɔ:lˈtɜ:nət]	 vt.交替，轮流",
"arouse	[əˈraʊz]	vt.使......奋发",
"array	[əˈreɪ]	n.排列，队形",
"articulate	[ɑ:ˈtɪkjuleɪt]	adj.发音清晰的，善于表达的",
"shatter	[ˈʃætə(r)]	 n.碎片；粉碎　v.粉碎；使疲惫；使震骇",
"shove	[ʃʌv]	 vt.乱推；乱塞  vi.用力推，挤  n.猛推",
"shuttle	[ˈʃʌtl]	 n.往返汽车/列车/飞机；穿梭  v.往返穿梭",
"segregate	[ˈsegrɪgeɪt]	 vt. separate or keep apart from others  分离，隔离",
"serial	[ˈsɪəriəl]	 n.连本影片，连本电视节目 a.连续的",
"setback	[ˈsetbæk]	 n.挫折；失效；复发；倒退",
"shabby	[ˈʃæbi]	 a.简陋的，破旧的；卑鄙的，不正当的",
"aggravate	[ˈægrəveɪt]	vt.加重，加剧，恶化",
"aggressive	[əˈgresɪv]	 adj.侵犯的，侵略的",
"allied	[ˈælaɪd]	adj.结盟的，有关联的",
"allowance	[əˈlaʊəns]	n.津贴，补贴，零用钱",
"alter	[ˈɔ:ltə(r)]	 vt.改变，更改",
"adverse	[ˈædvɜ:s]	adj.不友好的，敌对的",
"advocate	[ˈædvəkeɪt]	 vt.拥护，提倡，主张n.提倡者; （辩护）律师; 支持者",
"aesthetic	[i:sˈθetɪk]	adj.美学的，艺术的，审美",
"affiliate	[əˈfɪlieɪt]	 vt.& vi使隶属（或附属）于，使成为会员",
"affirm	[əˈfɜ:m]	 vt.& vi断言，申明",
"artificial	[ˌɑ:tɪˈfɪʃl]	adj.人工的，人造的，人为的",
"ascend	[əˈsend]	vi&vt.登高，（渐渐）上升，升高",
"ascertain	[ˌæsəˈteɪn]	vt.查明，弄清，确定",
"ashamed	[əˈʃeɪmd]	adj.惭愧的，羞耻的",
"ashore	[əˈʃɔ:(r)]	adv.向岸，向陆地",
"aside	[əˈsaɪd]	 prep在旁边",
"assimilate	[əˈsɪməleɪt]	vi&vt.吸收，消化",
"associate	[əˈsəʊʃieɪt]	vi&vt.（使）联系，（使）结合",
"bar	[bɑ:(r)]	n.条，块，杆，棒, 酒吧",
"assault	[əˈsɔ:lt]	 n.攻击，袭击",
"assemble	[əˈsembl]	 vt.& vi.集合，召集",
"assert	[əˈsɜ:t]	 vt.肯定地说（出），坚定地断言",
"assess	[əˈses]	vt.估价，评价，评论",
"assign	[əˈsaɪn]	vt.分配，布置（作业",
"beforehand	[bɪˈfɔ:hænd]	adv.预先，事先",
"bewilder	[bɪˈwɪldə(r)]	vt.使迷惑，使糊涂",
"boom	[bu:m]	n.低沉有回响的声音",
"bore	[bɔ:(r)]	vt&vi.钻孔，挖（通道",
"bounce	[baʊns]	 vi&vt.弹起，反弹",
"sovereign	[ˈsɒvrɪn]	 a.独立的，有主权的 n.君主，国王，统治者",
"spacious	[ˈspeɪʃəs]	 adj.广阔的，宽敞的",
"spectrum	[ˈspektrəm]	 n.谱，光谱，频谱；范围，幅度，系列",
"spicy	[ˈspaɪsi]	 a.加很多香料的；(口味)浓郁的",
"spine	[spaɪn]	 n.脊柱，脊椎；(动植物的)刺；书脊",
"bound	[baʊnd]	vi&vt.跳跃，弹回",
"boycott	[ˈbɔɪkɒt]	vt.（联合起来）抑制，拒绝参加",
"brace	[breɪs]	 vt.支撑; n.支持物; 铁钳，托架，支架",
"breed	[bri:d]	vt.（使）繁殖",
"bribe	[braɪb]	vt&n.贿赂",
"anchor	[ˈæŋkə(r)]	锚",
"Annoy	[əˈnɔɪ]	 vt.使恼怒，使生气",
"annual	[ˈænjuəl]	adj.每年的，年度的",
"anonymous	[əˈnɒnɪməs]	 adj.匿名的，无名的",
"anticipate	[ænˈtɪsɪpeɪt]	 vt.&vi预期，预料",
"apart	[əˈpɑ:t]	 adv.&ad.j成零碎",
"Apparent	[əˈpærənt]	 adj.显然的，明明白白的",
"brisk	[brɪsk]	adj. 轻快的，生气勃勃的",
"brittle	[ˈbrɪtl]	 adj.易碎的，一碰就破的",
"appoint	[əˈpɔɪnt]	 vt.任命，委派",
"appraise	[əˈpreɪz]	 vt.估量，估计",
"appreciate	[əˈpri:ʃieɪt]	 vt.感激",
"apprehend	[ˌæprɪˈhend]	vt&vi对...担心",
"appropriate	[əˈprəʊpriət]	adj.恰当的，相称的",
"approve	[əˈpru:v]	 vt.& vi赞成，同意",
"accumulate	[əˈkju:mjəleɪt]	 vt.& vi积累，积攒，积聚",
"accurate	[ˈækjərət]	adj.准确的，精确的",
"accuse	[əˈkju:z]	 v.指控，指责",
"activate	[ˈæktɪveɪt]	 使活动起来，使开始起作用，启动",
"bump	[bʌmp]	 vt.& vi.碰，撞",
"burst	[bɜ:st]	vi&vt 爆炸，爆裂",
"casual	[ˈkæʒuəl]	adj.偶然的，无计划的，随便的，非正式的",
"cease	[si:s]	 vt.&vi.停止，终止，结束",
"certify	[ˈsɜ:tɪfaɪ]	 vt.证明，证实",
"challenge	[ˈtʃæləndʒ]	vt.向...挑战",
"character	[ˈkærəktə(r)]	n.（事物的）性质，特质",
"secure	[sɪˈkjʊə(r)]	adj.安全的，可靠的，有把握的",
"sensible	[ˈsensəbl]	adj.明知的，合情理的",
"approximate	[əˈprɒksɪmət]	 adj.大概的，大约的，近似的",
"apt	[æpt]	adj.（习性）易于......的，有......倾向的",
"Arbitrary	[ˈɑ:bɪtrəri]	adj. 随心所欲的，个人武断的，任意的",
"arise	[əˈraɪz]	 vi.& vt 起立，起身",
"blaze	[bleɪz]	 n.火焰",
"aggravate	[ˈægrəveɪt]	 vt.加重，加剧，恶化",
"aggressive	[əˈgresɪv]	adj. 侵犯的，侵略的",
"allied	[ˈælaɪd]	adj.结盟的，有关联的",
"allowance	[əˈlaʊəns]	n. 津贴，补贴，零用钱",
"alter	[ˈɔ:ltə(r)]	vt&vi. 改变，更改",
"charge	[tʃɑ:dʒ]	 n&vi&vt.要（价），收（费",
"charm	[tʃɑ:m]	 n.魅力，魔力",
"chase	[tʃeɪs]	 vi&vt&n.追逐，追求",
"Check	[tʃek]	 vt.使突然停止，制止",
"cherish	[ˈtʃerɪʃ]	vt. 珍爱，珍视",
"chew	[tʃu:]	 vt.& vi嚼，咀嚼",
"choke	[tʃəʊk]	 vt.& vi.窒息，噎住",
"bias	[ˈbaɪəs]	 n.偏见，偏心",
"blame	[bleɪm]	vt. 责备，责怪",
"blast	[blɑ:st]	n.一阵（风），一股（气流",
"alternate	[ɔ:lˈtɜ:nət]	 vi&vt.交替，轮流",
"arouse	[əˈraʊz]	vt. 使......奋发",
"array	[əˈreɪ]	排列，队形",
"articulate	[ɑ:ˈtɪkjuleɪt]	 adj.发音清晰的，善于表达的",
"boast	[bəʊst]	n. 自吹自擂，自夸的话",
"bolt	[bəʊlt]	 n.螺栓，（门，窗的）插销",
"confuse	[kənˈfju:z]	vt.使混乱，混淆",
"Corrupt	[kəˈrʌpt]	adj.堕落的,腐败的,贪赃舞弊的",
"Count	[kaʊnt]	v.数,计算",
"Course	[kɔ:s]	n.课程,科目",
"courtesy	[ˈkɜ:təsi]	n.谦恭有礼。有礼的举止（或）言辞",
"credit	[ˈkredɪt]	n.信任，可信性；学分",
"shade	[ʃeɪd]	n.荫，荫凉处",
"sham	[ʃæm]	n.假装，虚伪",
"shear	[ʃɪə(r)]	vt.&vi剪，修剪",
"shed	[ʃedvt&vi&n.]	流",
"sheer	[ʃɪə(r)]	adj.完全的，十足的",
"shelter	[ˈʃeltə(r)]	n.掩蔽处，躲避处",
"connect	[kəˈnekt]	 vt&vi.连接，连接",
"conscious	[ˈkɒnʃəs]	adj.意识到的，自觉地",
"consent	[kənˈsent]	vi&n. 同意，赞同，准许",
"conserve	[kənˈsɜ:v]	 vt&n.保护，保藏，保存",
"consist	[kənˈsɪst]	vi.组成，构成",
"consolidate	[kənˈsɒlɪdeɪt]	vt&vi巩固，加强",
"conspicuous	[kənˈspɪkjuəs]	adj显眼的，明显的，引人瞩目的",
"Contrary	[ˈkɒntrəri]	adj.相反的,对抗的",
"Contrast	[ˈkɒntrɑ:st]	vi&vt对照,对比,(对比之下显出的)差异",
"Contribute	[kənˈtrɪbju:t]	 vt.& vi捐(款等),捐献",
"Contrive	[kənˈtraɪv]	 vt.设计,想出",
"corrode	[kəˈrəʊd]	 vt.& vi. (渐渐)损害,(一点一点地)损伤",
"dawn	[dɔ:n]	n. 黎明，拂晓",
"dazzle	[ˈdæzl]	vt.（强光等）使目眩，耀眼",
"deceive	[dɪˈsi:v]	v.欺骗，蒙蔽",
"decent	[ˈdi:snt]	adj.体面的，像样的",
"decline	[dɪˈklaɪn]	 vt.& vi.拒绝，谢绝",
"appeal	[əˈpi:l]	vt.呼吁，恳求",
"applaud	[əˈplɔ:d]	vt.&vi 鼓掌，喝彩，叫好",
"apply	[əˈplaɪ]	 vt.申请;涂，敷",
"chorus	[ˈkɔ:rəs]	 n.合唱队",
"chronic	[ˈkrɒnɪk]	adj.（疾病）慢性的，（人）久病的",
"clarity	[ˈklærəti]	n.澄清，阐明",
"cling	[klɪŋ]	 vi&vt.粘着",
"clumsy	[ˈklʌmzi]	adj.笨拙的",
"monitor	[ˈmɒnɪtə(r)]	n.班长 ；vt.监控",
"mortgage	[ˈmɔ:gɪdʒ]	n.&vt 抵押（借款",
"motion	[ˈməʊʃn]	n.动，运动",
"motive	[ˈməʊtɪv]	n.动机，目的",
"mount	[maʊnt]	 vt.& vi.登上， 爬上",
"cluster	[ˈklʌstə(r)]	n.（果实，花等的）串，束，簇; (人或物)的群，组",
"clutch	[klʌtʃ]	vt.紧抓，紧握",
"coherent	[kəʊˈhɪərənt]	 adj.一致的，协调的",
"cure	[kjʊə(r)]	vt.治愈，医治",
"cut	[kʌt]	 vt.& vi.切，割，剪，砍，削",
"screen	[skri:n]	 n.屏，幕，帘",
"decompose	[ˌdi:kəmˈpəʊz]	 vt.& vi.分解，腐烂，腐败",
"dedicate	[ˈdedɪkeɪt]	 vt.奉献，把。。。用在",
"deduce	[dɪˈdju:s]	vt.演绎，推论",
"define	[dɪˈfaɪn]	vt.&vi解释，给。。。下定义",
"Deform	[dɪˈfɔ:m]	vt.&vi (使)变形",
"constant	[ˈkɒnstənt]	 adj.经常的，不断的",
"constitute	[ˈkɒnstɪtju:t]	 vt.组成，构成",
"consult	[kənˈsʌlt]	vi&vt.请教，与......商量",
"consume	[kənˈsju:m]	vt.消费,花费",
"contact	[ˈkɒntækt]	n.&vt接触,联系,交往",
"contain	[kənˈteɪn]	vt.包括,容纳",
"contaminate	[kənˈtæmɪneɪt]	 vt.弄脏,污染,玷污,毒害",
"calculate	[ˈkælkjuleɪt]	 vt.& vi.计算，推算",
"call	[kɔ:l]	 v. 喊，叫",
"cancel	[ˈkænsl]	vt. 取消，废除，删去",
"capture	[ˈkæptʃə(r)]	vt. 俘虏，捕获",
"assume	[əˈsju:m]	假定，假设",
"assure	[əˈʃʊə(r)]	 vt.深信不疑地对......说，向......保证",
"assurance	[əˈʃʊərəns]	 n.保证，把握，信心",
"astonish	[əˈstɒnɪʃ]	 vt.使惊讶",
"attach	[əˈtætʃ]	 vt.& vi.系，贴，连接",
"attain	[əˈteɪn]	 vt.& vi达到，获得",
"attend	[əˈtend]	vi&vt.出席，参加（会议等",
"attendance	[əˈtendəns]	 n.出席，参加，出席人数，出席率",
"attentive	[əˈtentɪv]	adj.注意的，专心的",
"attribute	[əˈtrɪbju:t]	 vt.把归因于，把......（过错的责任等）归于",
"auxiliary	[ɔ:gˈzɪliəri]	adj.辅助的",
"avail	[əˈveɪl]	 vt.& vi.有利于，有助于",
"average	[ˈævərɪdʒ]	n.平均数,平均",
"avert	[əˈvɜ:t]	 挡开，防止，避免",
"ban	[bæn]	vt.&n.（以官方明令）禁止，取缔",
"bang	[bæŋ]	 n. （突发的）猛击; 猛撞; 巨响; 爆炸声",
"cast	[kɑ:st]	vt.投，扔，抛，撒，掷",
"contempt	[kənˈtempt]	n.轻视,轻蔑",
"contest	[ˈkɒntest]	n.&vt&vi.竞赛,比赛,竞争",
"contract	[ˈkɒntrækt]	n.合同,契约",
"contradict	[ˌkɒntrəˈdɪkt]	vt&vi.反驳,同….相矛盾,同….相抵触",
"defy	[dɪˈfaɪ]	vt.&n.公然违抗，反抗",
"degenerate	[dɪˈdʒenəreɪt]	n.衰退，堕落，变坏",
"deliberate	[dɪˈlɪbərət]	adj.慎重的，深思熟虑的",
"denote	[dɪˈnəʊt]	 vt.表示，是。。。的标志，意思是",
"Correspond	[ˌkɒrəˈspɒnd]	 vi.相符合相称",
"Correspondent	[ˌkɒrəˈspɒndənt]	n.通信者,通讯员,记者",
"Corresponding	[ˌkɒrəˈspɒndɪŋ]	adj.符合的,一致的",
"compact	[kəmˈpækt]	 vt.& vi. 紧密的，坚实的",
"compare	[kəmˈpeə(r)]	 vt.& vi.比较，对照",
"compatible	[kəmˈpætəbl]	adj. 能和睦相处的，合的来的",
"detain	[dɪˈteɪn]	vt.留住，担搁",
"detect	[dɪˈtekt]	vt.（当场）发现（某人在干坏事",
"deteriorate	[dɪˈtɪəriəreɪt]	vt.&vi（使）恶化,(使)变坏,(使)退化",
"deviate	[ˈdi:vieɪt]	v.背离，偏离",
"devote	[dɪˈvəʊt]	vt.将...献给",
"compile	[kəmˈpaɪl]	vt.汇编，编制",
"comply	[kəmˈplaɪ]	vi.遵从，顺从，服从",
"compose	[kəmˈpəʊz]	vt.组成，构成",
"compress	[kəmˈpres]	vt.压缩",
"comprise	[kəmˈpraɪz]	vt.包含，包括",
"compromise	[ˈkɒmprəmaɪz]	 n.&vi.&vt.妥协，折衷",
"confront	[kənˈfrʌnt]	 vt.（使）面临，（使）遭遇",
"crucial	[ˈkru:ʃl]	adj.决定性的，关键性的",
"cue	[kju:]	n.提示，暗号，信号",
"cultivate	[ˈkʌltɪveɪt]	vt.耕作，栽培，养殖",
"differentiate	[ˌdɪfəˈrenʃieɪt]	 vt.& vi.使不同，使有差别，区分，区别",
"diffuse	[dɪˈfju:s]	vi.&vt.扩散（气体，液体等",
"disgust	[dɪsˈgʌst]	vt.厌恶，恶心",
"disperse	[dɪˈspɜ:s]	 vt.& vi.分散，驱散，散去",
"displace	[dɪsˈpleɪs]	 vt.移走; 替换，移动。。。的位置",
"dispose	[dɪˈspəʊz]	 vt.& vi.布置，整理",
"disregard	[ˌdɪsrɪˈgɑ:d]	vt.不理会，不顾",
"distinct	[dɪˈstɪŋkt]	adj.有区别的，不同的",
"distort	[dɪˈstɔ:t]	vt.&vi扭歪，扭曲：a face distorted by (或",
"distract	[dɪˈstrækt]	vt.使转向",
"distribute	[dɪˈstrɪbju:t]	 vt.分配，分发",
"eliminate	[ɪˈlɪmɪneɪt]	vt.排除,消除",
"elite	[eɪˈli:t]	n.出类拔萃的人(或物),精华",
"eloquent	[ˈeləkwənt]	adj.雄辩的,口才流利的,有说服力的",
"embark	[ɪmˈbɑ:k]	vi.上船(或飞机,汽车等):embark for Europe at New York harborvt.vt.使…上船或飞机",
"embody	[ɪmˈbɒdi]	vt.使具体化,表现",
"embrace	[ɪmˈbreɪs]	 vt.& vi.拥抱",
"enlighten	[ɪnˈlaɪtn]	vt.启发,使摆脱偏见(或迷信",
"enroll	[ɪn'rəʊl]	v.吸收(成员),招生",
"ensure	[ɪn'ʃʊə(r)]	vt.保证,担保",
"diminish	[dɪˈmɪnɪʃ]	vt.减少，降低",
"diplomat	[ˈdɪpləmæt]	n.外交家，外交官，圆滑的人",
"discard	[dɪsˈkɑ:d]	vt.丢弃，抛弃",
"discern	[dɪˈsɜ:n]	vt.看出，觉察出",
"disclose	[dɪsˈkləʊz]	vt.揭露，透露，使公开",
"discharge	[dɪsˈtʃɑ:dʒ]	 vt.& vi.释放",
"discount	[ˈdɪskaʊnt]	vt.把（价格，费用等）打折扣，削价出售",
"discriminate	[dɪˈskrɪmɪneɪt]	 vt.& vi.区别，辨别",
"disgrace	[dɪs'greɪs]	 n.丢脸，耻辱",
"entertain	[entə'teɪn]	 vt.给。。。娱乐,使有兴趣",
"entitle	[ɪn'taɪt(ə)l; en-]	 vt.给。。。权利,给。。。资格",
"equivalent	[ɪ'kwɪv(ə)l(ə)nt]	 adj.相等的,相同的",
"erase	[ɪ'reɪz]	 vt.擦掉,抹掉,消除",
"erect	[ɪ'rekt]	 adj.竖直的,垂直的,竖起的",
"erupt	[ɪ'rʌpt]	  vt.(火山,喷泉等)喷发",
"essence	['es(ə)ns]	 n.本质,实质,要素",
"eternal	[ɪˈtɜ:nl]	 adj.永恒的,永存的,永久的",
"evaluate	[ɪ'væljʊeɪt]	 vt.估价,评价",
"evaporate	[ɪ'væpəreɪt]	  vt.(使)蒸发,(使)挥发",
"exaggerate	[ɪg'zædʒəreɪt; eg-]	 vi.夸张,夸大,对…言过其实",
"exceed	[ɪk'siːd]	 vt.超出,胜过",
"external	[ɪk'stɜːn(ə)l]	 adj.外面的,外部的",
"descend	[dɪ'send]	 vi.下来，下降",
"Extract	[ˈekstrækt]	 vt.取出,提取",
"Extravagant	[ɪk'strævəg(ə)nt; ek-]	 adj.奢侈的,浪费的",
"fabricate	['fæbrɪkeɪt]	 vt.建造,制造",
"facilitate	[fə'sɪlɪteɪt]	 vt.使变得(更)容易,使便利",
"fade	[feɪd]	  vi.(颜色)褪去",
"faint	[feɪnt]	 adj.不清楚的,模糊的,微弱的",
"fancy	['fænsɪ]	 n.想象力",
"fare	[feə]	 n.车费,船费,飞机票价",
"divorce	[dɪ'vɔːs]	 n.离婚，分离，脱离",
"dominate	['dɒmɪneɪt]	 vt.分配，统治",
"donate	[də(ʊ)'neɪt]	 vt.捐赠，赠送",
"doom	[duːm]	 n.命运，厄运，劫数",
"doze	[dəʊz]	 vi.打瞌睡，打盹儿",
"drain	[dreɪn]	 vi.慢慢排去",
"dread	[dred]	 vt.怕，畏惧",
"drift	[drɪft]	 vi.漂流，漂泊",
"dubious	['djuːbɪəs]	 adj.引起怀疑的，不确定的",
"due	[djuː]	 adj.欠款的，应支付的",
"Dump	[dʌmp]	 vt.倾倒，倾卸",
"Duplicate	[ˈdjuːplɪkeɪt]	 adj.完全一样的，复制的",
"excess	[ɪk'ses; ek-; 'ekses]	 n.超越,超过",
"execute	['eksɪkjuːt]	 vt.实行,实施,执行,履行",
"exemplify	[ɪg'zemplɪfaɪ; eg-]	 vt.例示,举例证明,是…的例证(或榜样等",
"exert	[ɪg'zɜːt; eg-]	 vt.用力,尽力",
"Exhaust	[ɪg'zɔːst; eg-]	 vt.汲空,抽完",
"expand	[ɪk'spænd; ek-]	 vt.扩大,扩展,膨胀",
"expel	[ɪk'spel; ek-]	 vt.驱逐,赶走",
"expend	[ɪk'spend; ek-]	 vt.花费,消费",
"expire	[ɪk'spaɪə; ek-]	 vi.满期,届期,(期限)终止",
"explicit	[ɪk'splɪsɪt; ek-]	 adj.详尽的,明确的",
"exploit	[ɪk'splɒɪt; ek-]	 n.英勇的或冒险的行为或事迹",
"exterior	[ɪk'stɪərɪə; ek-]	 adj.外部的,外面的,外表的",
"durable	['djʊərəb(ə)l]	 adj.耐用的",
"dwell	[dwel]	 vi.（dwelt 或 dwelled ）（尤指作为常住居民）居住",
"economical	[iːkə'nɒmɪk(ə)l; ek-]	 adj.节约的,节俭的,经济的",
"generate	['dʒenəreɪt]	 vt.产生，发生(电、热、光、力、摩擦力等",
"genuine	['dʒenjʊɪn]	 adj.真的，非人造的，名副其实的",
"gesture	['dʒestʃə]	 n.手势，示意动作",
"confine	[kən'faɪn]	 vt.限制，使局限",
"confirm	[kən'fɜːm]	 vt.证实，肯定",
"conflict	['kɒnflɪkt]	 n.（尤指长期的）战争，战斗",
"conform	[kən'fɔːm]	 vt.遵照，适应  confirm to(或",
"flourish	['flʌrɪʃ]	 n.茂盛,繁荣,兴旺",
"fluctuate	['flʌktʃʊeɪt; -tjʊ-]	 vt.波动,起伏",
"flush	[flʌʃ]	 vt.脸红",
"forbid	[fə'bɪd]	 vt.不许,禁止",
"forge	[fɔːdʒ]	 n.锻炼",
"glance	[glɑːns]	 n.一瞥，扫视",
"glare	[gleə]	 n.怒视，瞪眼",
"dense	[dens]	 adj.稠密的，密集的",
"deposit	[dɪ'pɒzɪt]	 vt.存放",
"Depress	[dɪ'pres]	 vt.使沮丧，使消沉",
"deprive	[dɪ'praɪv]	 vt. 剥夺，使丧失",
"derive	[dɪ'raɪv]	 vt.取得，得到",
"controversy	['kɒntrəvɜːsɪ; kən'trɒvəsɪ]	  n.(尤之以文字形式进行的争论),辨证",
"convention	[kən'venʃ(ə)n]	  n.(正式)会议,(定期)大会",
"convert	[kən'vɜːt]	 vt.转变,转化",
"convey	[kən'veɪ]	 vt.运送,输送,传送",
"convict	[kən'vɪkt]	  vt.(经审讯)证明…有罪,宣判…有罪",
"coordinate	[kəʊ'ɔ:dɪneɪt]	 vt.调节,协调",
"cordial	['kɔːdɪəl]	 adj.热情友好的,热诚的,真心的",
"glimpse	[glɪm(p)s]	 n.一瞥，一看",
"glitter	['glɪtə]	 vi.闪闪发亮(或发光)，光彩夺目，闪耀",
"glory	['glɔːrɪ]	 n.光荣，荣誉",
"glow	[gləʊ]	 vi.发热，发光，发红",
"gossip	['gɒsɪp]	 n.流言蜚语",
"govern	['gʌv(ə)n]	 vt.统治，管理",
"grace	[greɪs]	 vt.优美",
"graduate	['grædʒʊət; -djʊət]	 vt. (使)大学毕业",
"grant	[grɑːnt]	 vt.同意，准予",
"grease	[griːs]	n.油脂，动物脂",
"heal	[hiːl]	vt.&vi.治愈，愈合",
"heap	[hiːp]	 n.(一)堆",
"hedge	[hedʒ]	 n.(矮树)树篱",
"highlight	['haɪlaɪt]	vt.使显著，使突出",
"fracture	['fræktʃə]	 vt.& vi.&n.裂缝,裂痕",
"frequent	['friːkw(ə)nt]	adj.时常发生的,频繁的",
"frown	[fraʊn]	 vt.& vi.皱眉",
"frustrate	[frʌ'streɪt; 'frʌs-]	vt.挫败,阻挠,使灰心,使无效",
"fulfill	[ful'fil]	 (fulfilled, fulfilling)vt.履行,实现,完成",
"furnish	['fɜːnɪʃ]	vt.供应，提供",
"fury	['fjʊərɪ]	n.狂怒，暴怒",
"fuss	[fʌs]	 vi.大惊小怪; 忙乱; 抱怨; vt.使烦恼，使烦忧; 使急躁; n.大惊小怪，乱忙，小题大做",
"hinder	['hɪndə]	 vt.& vi妨碍，阻止",
"hint	[hɪnt]	n.暗示",
"enforce	[ɪn'fɔːs; en-]	vt.实施,使生效",
"engage	[ɪn'geɪdʒ; en-]	 vt.(用契约诺言等)约束,使订婚",
"enhance	[ɪn'hɑːns; -hæns; en-]	vt.提高(价格,质量,吸引力等),增加,增强",
"figure	['fɪgə]	n.数字",
"finance	[faɪ'næns; fɪ-; 'faɪnæns]	n.财政,金融",
"finite	['faɪnaɪt]	adj.有限的,有限制的",
"flare	[fleə]	 vt.&vi(火焰)闪耀,(摇曳不定地)燃烧",
"flash	[flæʃ]	 vt.& vi.闪光,闪烁",
"flat	[flæt]	adj.平坦的,扁平的",
"inaccessible	[ɪnək'sesɪb(ə)l]	adj.达不到的",
"incline	[ɪn'klaɪn]	 vt.& vi.倾斜",
"incorporate	[ɪn'kɔːpəreɪt]	vt.&vi.包含，吸收",
"incur	[ɪn'kɜː]	vt.招致，引起，遭受",
"modify	['mɒdɪfaɪ]	vi.&vt.修改，更改",
"momentary	['məʊm(ə)nt(ə)rɪ]	adj.片刻的，瞬息的",
"designate	['dezɪgneɪt]	vt.指明，表明",
"desolate	['des(ə)lət]	adj.荒芜的，不毛的",
"despise	[dɪ'spaɪz]	vt.蔑视，鄙视",
"detach	[dɪ'tætʃ]	vt.拆卸",
"Diagnose	['daɪəgnəʊz; -'nəʊz]	vt&vi.诊断，判断",
"dictate	[dɪk'teɪt]	vt.&vi口授，使听写",
"coincide	[,kəʊɪn'saɪd]	vi相符，相一致",
"collaborate	[kə'læbəreɪt]	vi（尤指在文艺、科学等方面）合作，协作",
"collapse	[kə'læps]	vi&vt.倒坍，崩溃，瓦解",
"collide	[kə'laɪd]	vi碰撞，互撞",
"commemorate	[kə'meməreɪt]	vt.纪念，庆祝",
"commend	[kə'mend]	vt.表扬，称赞",
"extinct	[ɪk'stɪŋkt; ek-]	 adj. (火等)熄灭了的",
"extinguish	[ɪk'stɪŋgwɪʃ; ek-]	vt.熄灭,扑灭",
"multiply	['mʌltɪplaɪ]	 vt.& vi.乘，相乘",
"muscle	['mʌs(ə)l]	n.肌肉",
"mutual	['mjuːtʃʊəl; -tjʊəl]	adj.相互的， 彼此的",
"narrate	[nə'reɪt]	vt&vi.叙述，讲述",
"negligent	['neɡlɪdʒənt]	 adj.疏忽的，大意的",
"indignant	[ɪn'dɪgnənt]	adj.愤怒的，愤慨的",
"indispensable	[ɪndɪ'spensəb(ə)l]	adj.必不可少的，必需的",
"induce	[ɪn'djuːs]	vt.引诱，劝使",
"infer	[ɪn'fɜː]	 vt.&vi(根据已知事实等)推断，推定",
"ingenious	[ɪn'dʒiːnɪəs]	 adj.(人,头脑等)灵巧的，足智多谋的",
"instant	['ɪnst(ə)nt]	adj.紧急的，急迫的，立即的，即刻的",
"institute	['ɪnstɪtjuːt]	n.学会，协会，学院，研究院",
"insulate	['ɪnsjʊleɪt]	vt.隔音，使隔绝(以免受到影响",
"insult	[ɪn'sʌlt]	vt.&n.侮辱，辱骂",
"flatter	['flætə]	vt.奉承,使高兴",
"Flee	[fliː]	vi&vt.逃走,逃掉",
"Flexible	['fleksɪb(ə)l]	 adj.灵活的; 柔韧的; 易弯曲的",
"fling	[flɪŋ]	 vt.& vi. (用力)扔,掷,抛,丢",
"hoist	[hɒɪst]	vt&vi.举起，升起，吊起",
"hold	[həʊld]	vt.拿着，抓住",
"homogeneous	[ˌhɒməˈdʒi:niəs]	 adj.同种类的，同性质的，有相同特征的",
"horizon	[hə'raɪz(ə)n]	地平(线",
"hospitable	[hɒˈspɪtəbl]	 adj好客的，殷勤的，热情友好的",
"hostile	['hɒstaɪl]	adj 敌人的，敌方的",
"withstand	[wɪð'stænd]	vi 经受，承受",
"speculate	['spekjʊleɪt]	 vi推测，推断",
"spill	[spɪl]	 vt溢出，溅出",
"spinvt纺		spin vt纺制",
"spit	[spɪt]	 vt吐出",
"splash	[splæʃ]	 vt 溅泼",
"split	[splɪt]	 vt 劈开，切开，裂开",
"spoil	[spɒɪl]	 vt损坏，毁掉",
"sponsor	['spɒnsə]	 n发起者，主办者，保证人，赞助者",
"spot	[spɒt]	 n斑点，污点",
"spray	[spreɪ]	 n浪花，水花",
"sprout	[sprəʊt]	vi 抽条，发芽，长出",
"spur	[spɜː]	 n靴刺，踢马刺",
"renovate	['renəveɪt]	 vt修复，整修",
"repel	[rɪ'pel]	 vt击退，抵制，拒绝，排斥",
"repent	[rɪ'pent]	 后悔，懊悔",
"replace	[rɪ'pleɪs]	 vt 代替，取代，更换",
"transmit	[trænz'mɪt; trɑːnz-; -ns-]	 vt播送，发射",
"transparent	[træn'spær(ə)nt; trɑːn-; -'speə-]	 adj透明的",
"transplant	[træns'plɑːnt; trɑːns-; -nz-]	 vt移植，移种，移居",
"treasure	['treʒə]	 n财宝，财富",
"trend	[trend]	 n倾向，趋势",
"trick	[trɪk]	 n诡计，骗局",
"trifle	['traɪf(ə)l]	 n琐事，小事",
"trim	[trɪm]	 adj整齐的，整洁的",
"triple	['trɪp(ə)l]	 adj三倍的，三重的，三部分的，三方的",
"triumph	['traɪʌmf]	 n 胜利",
"trivial	['trɪvɪəl]	 adj琐碎的，不重要的，无价值的",
"tuck	[tʌk]	 vt 夹入，藏入",
"tug	[tʌg]	 vt（用力）拖或拉",
"stroke	[strəʊk]	 vt敲，打，鸣",
"tend	[tend]	 vi趋向，倾向",
"tender	['tendə]	 adj嫩的",
"represent	[reprɪ'zent]	 vt 代表，象征",
"reproach	[rɪ'prəʊtʃ]	 n责备，指责，斥责",
"scratch	[skrætʃ]	 vt抓，刮，擦",
"shield	[ʃiːld]	 n 盾，保护物，防御物",
"snob	[snɒb]	 n势力的人，谄上欺下的人",
"soak	[səʊk]	 vi 湿透，浸湿，浸泡",
"sobe	['səʊbə]	 adj未醉的",
"sophisticated	[sə'fɪstɪkeɪtɪd]	老于世故的",
"sore	[sɔː]	 adj 痛的，痛苦的，痛心的",
"sow	[səʊ]	 vt播种",
"spark	[spɑːk]	 n火花，火星",
"sparkle	['spɑːk(ə)l]	 n发光，闪耀",
"tentative	['tentətɪv]	 adj 试验性的，试探性的，暂时的，推测的",
"terminate	['tɜːmɪneɪt]	 vt停止，结束，使终止",
"terrify	['terɪfaɪ]	 vt使害怕，使惊吓",
"testify	['testɪfaɪ]	 vt 作证，证明",
"humble	['hʌmbl]	 adj 地位(或身份)低下的，卑贱的",
"hysterical	[hɪ'sterɪk(ə)l]	 adj情绪异常激动的，歇斯底里的",
"identical	[aɪ'dentɪk(ə)l]	 adj同一的",
"identify	[aɪ'dentɪfaɪ]	 vt识别，鉴别",
"idle	['aɪd(ə)l]	 adj闲散的，闲置的",
"ignite	[ɪg'naɪt]	 vt点燃，使燃烧",
"impose	[ɪm'pəʊz]	vi 征(税)，加(负担，惩罚等)于",
"impulse	['ɪmpʌls]	 vt推动，驱动",
"intact	[ɪn'tækt]	 adj完整无缺的，未经触动的，未受损伤的",
"integrate	['ɪntɪgreɪt]	 vt使成一体，使合并",
"interfere	[ɪntə'fɪə]	 vi 妨碍，冲突",
"intermittent	[ɪntə'mɪt(ə)nt]	 adj 间歇的，断断续续的，周期性的",
"hazard	['hæzəd]	 n危险，危害物，危险之源",
"label	['leɪb(ə)l]	n 标签，标记，标号",
"lag	[læg]	 n 走得慢，落后，滞留",
"latent	['leɪt(ə)nt]	 adj潜在的，隐伏的，不易觉察的",
"leak	[liːk]	 n漏洞，裂缝",
"lean	[liːn]	 vi 斜，倾斜",
"initiate	[ɪ'nɪʃɪeɪt]	vt 开始，发起",
"innovate	['ɪnəveɪt]	 vi革新，改革，创新",
"inquire	[ɪn'kwaɪə]	 vt 询问，打听",
"insert	[ɪn'sɜːt]	 vt插入，嵌入",
"inspire	[ɪn'spaɪə]	 vt鼓舞，激起",
"tumble	['tʌmb(ə)l]	 vi 跌到，滚下",
"tune	[tjuːn]	 n曲调，曲子",
"turbulent	['tɜːbjʊl(ə)nt]	 adj骚乱的，动荡的，混乱的，狂暴的",
"turn	[tɜːn]	 vt 转动，旋转",
"tutor	['tjuːtə]	 n家庭教师，指导教师",
"twinkle	['twɪŋk(ə)l]	 vt 闪烁，闪耀，闪亮",
"twist	[twɪst]	 vt 捻，搓，绞，拧",
"whistle	['wɪs(ə)l]	 n 吹口哨，鸣笛",
"whitewash	['waɪtwɒʃ]	 n粉饰",
"wholesome	['həʊls(ə)m]	 adj有益于健康的",
"wicked	['wɪkɪd]	 adj坏的，邪恶的，淘气的，恶作剧的",
"tease	[tiːz]	vt戏弄，取笑",
"tedious	['tiːdɪəs]	 adj单调乏味的，冗长的，罗嗦的",
"liable	['laɪəb(ə)l]	 adj会……的，有……倾向的",
"liberal	['lɪb(ə)r(ə)l]	 adj 慷慨的，大方的",
"limp	[lɪmp]	 adj软的，松沓的",
"linger	['lɪŋgə]	 vi逗留，徘徊",
"lubricate	['luːbrɪkeɪt]	 vt使润滑",
"lump	[lʌmp]	 n块，小方块",
"macroscopic	[,mækrə(ʊ)'skɒpɪk]	 adj肉眼可见的",
"magnet	['mægnət]	 n 磁铁，磁铁石",
"magnify	['mægnifaiiŋ]	 v 放大，扩大",
"maintain	[meɪn'teɪn; mən'teɪn]	 vt维持，保持",
"malfunction	[mæl'fʌŋ(k)ʃ(ə)n]	 vi 发生功能障碍，发生障碍",
"maltreat	[mæl'tritmənt]	 n 粗暴地对待，虐待",
"manifest	['mænɪfest]	 adj显然的，明了的",
"model	['mɒdl]	  n模型，原形",
"nominal	['nɒmɪn(ə)l]	 adj 名义的，有名无实的",
"nominate	['nɒmɪneɪt]	vt 提名",
"noteworthy	['nəʊtwɜːðɪ]	 adj值得注意的，显著的",
"intervene	[ɪntə'viːn]	 vi插入，介入",
"intricate	['ɪntrɪkət]	adj 错综复杂的，复杂精细的",
"invert	[ɪn'vɜːt]	 vt使反向，使倒转，使颠倒",
"irrespective	[ɪrɪ'spektɪv]	 adj 不考虑的，不顾的",
"irritate	['ɪrɪteɪt]	 vt 激怒，使恼怒，使烦躁",
"justify	['dʒʌstɪfaɪ]	 vt证明。。。正当或有理,正确",
"knit	[nɪt]	 vt 编织，编结",
"greet	[griːt]	 vt 问候，招呼",
"grieve	[griːv]	 vt 使悲伤，使伤心",
"grind	[graɪnd]	 vt  (ground)磨，磨碎，碾碎",
"grip	[grɪp]	 vt抓紧，紧握",
"gross	[grəʊs]	 adj 总的，毛的",
"guarantee	[gær(ə)n'tiː]	 n保证，保证书，保单",
"hail	[heɪl]	 vt 欢呼，喝彩",
"halt	[hɔːlt]	 vt (行进中的)暂停前进，中止，终止",
"hamper	['hæmpə]	 vt 妨碍，阻碍",
"handicap	['hændɪkæp]	 障碍，不利条件",
"haste	[heɪst]	 n急速，急忙，仓促，草率",
"hatch	[hætʃ]	 vt 孵，孵出",
"manipulate	[mə'nɪpjʊleɪt]	vt (熟练地)操作",
"mature	[mə'tʃʊə]	 adj 熟的，成熟的",
"melt	[melt]	 vt 使融化，使熔化",
"mend	[mend]	 vt 修理，修补",
"merit	['merɪt]	 n 长处，优点，价值，功绩",
"migrate	[maɪ'greɪt; 'maɪgreɪt]	 vi 移居(尤指移居国外)，迁移",
"minimum	['mɪnɪməm]	 n最低限度，最少量，最低点",
"minor	['maɪnə]	 adj较小的，较少的，较不重要的",
"mislead	[mɪs'liːd]	 vt 把……引错方向，把……引入歧途",
"moan	[məʊn]	 n呻吟声，呜咽声",
"mobilize	['məʊbəlaɪz]	 vt 动员",
"Mock	[mɒk]	 vt 嘲笑，嘲弄",
"Ornament	['ɔːnəm(ə)nt]	n 装饰品，点缀品",
"orthodox	['ɔːθədɒks]	 adj正统的，正宗的",
"outline轮廓，外		outline轮廓，外形",
"overflow	[əʊvə'fləʊ]	 n泛滥",
"overhaul	[əʊvə'hɔːl]	vt 大修，全面检查，彻底革新",
"overhear	[əʊvə'hɪə]	vt 偶然听到，偷听到",
"occupy	['ɒkjʊpaɪ]	 vt占用，占有",
"occur	[ə'kɜː]	发生，存在，出现",
"odd的奇数的，单的，奇怪		odd的奇数的，单的，奇怪的",
"wicked	['wɪkɪdli]	 adj坏的，邪恶的，淘气的，恶作剧的",
"wind	[wɪnd]	vi 绕，缠",
"Wire	[waɪə]	 n金属丝，金属线",
"withdraw	[wɪð'drɔː]	抽回，收回，提取",
"withhold	[wɪð'həʊld]	vt 使停止，阻挡",
"withstand	[wɪð'stænd]	vt 经受，承受",
"witness	['wɪtnɪs]	 n目击者，见证人",
"offend	[ə'fend]	vt 冒犯，使生气",
"offence	[ə'fens]	 n 犯法行为，过错",
"offset	['ɒfset]	 vt补偿，抵消",
"Omit	[ə(ʊ)'mɪt]	 vt 省略，删去",
"overlap	[əʊvə'læp]	 n 重叠，部分相同",
"overtake	[əʊvə'teɪk]	 vt赶上，超过",
"overthrow	[əʊvə'θrəʊ]	 vt推翻，打倒",
"overwhelm	[əʊvə'welm]	vt 征服，压倒，毁坏",
"pace	[peɪs]	 n 步，步速，步伐",
"pack	[pæk]	n 包，包裹",
"pad	[pæd]	 n垫，衬垫",
"pant	[pænt]	  vi 气喘，气喘吁吁地说话",
"parallel	['pærəlel]	 adj 平行的",
"patent	['pæt(ə)nt; 'peɪt(ə)nt]	n专利，专利权，专利品",
"pattern	['pæt(ə)n]	n 模范，榜样",
"periodical	[pɪərɪ'ɒdɪk(ə)l]	 adj期刊，杂志",
"perish	['perɪʃ]	vi 卒，丧生",
"perpetual	[pə'petʃʊəl; -tjʊəl]	adj 永久的，永恒的，长期的",
"pool水池，游泳		pool 水池，游泳池",
"notorious	[nə(ʊ)'tɔːrɪəs]	 adj臭名昭著的",
"notwithstanding	[nɒtwɪð'stændɪŋ; -wɪθ-]	adv 虽然，尽管",
"nourish	['nʌrɪʃ]	 vt养育",
"numb	[nʌm]	 adj麻木的，失去感觉的",
"object	['ɒbdʒɪkt; -dʒekt]	 n 物体，事物",
"objective	[əb'dʒektɪv]	 n目的，宗旨",
"oblige	[ə'blaɪdʒ]	 vt 强迫，迫使",
"obscure	[əb'skjʊə]	 adj 晦涩的，费解的",
"nasty	['nɑːstɪ]	 adj龌龊的，肮脏的",
"necessitate	[nɪ'sesɪteɪt]	 vt 使成为必须，需要",
"necessity	[nɪ'sesɪtɪ]	 必要（性），（迫切）需要",
"neglect	[nɪ'glekt]	 vt忽视，忽略",
"obsolete	['ɒbsəliːt]	 adj 废弃的，淘汰的",
"obstinate	['ɒbstɪnət]	 adj  顽固的，固执的，倔强的",
"occasion	[ə'keɪʒ(ə)n]	 n时刻，场合",
"opaque	[ə(ʊ)'peɪk]	 adj 不透明的",
"optimistic	[ɒptɪ'mɪstɪk]	 adj  乐观的，乐观主义的",
"option	['ɒpʃ(ə)n]	 n选择权",
"orient	['ɔːrɪənt; 'ɒr-]	 n东方，东方国家",
"origin	['ɒrɪdʒɪn]	 n 起源，由来",
"portable	['pɔːtəb(ə)l]	 adj 便于携带的，手提式的，轻便的",
"pose姿势，样		pose 姿势，样子",
"postpone	[pəʊs(t)'pəʊn; pə'spəʊn]	 vt 延迟，延缓，延期",
"potential	[pəˈtenʃl]	 adj 潜在的，可能的",
"rally	['rælɪ]	 vt集合，团结",
"paralyze	['pærə,laɪz]	 vt 使瘫痪，使麻痹",
"partial	['pɑːʃ(ə)l]	 adj 偏向一方的，偏袒的，偏爱的",
"participate	[pɑː'tɪsɪpeɪt]	 vt 参与，参加",
"particularpə'tɪkjʊlə]adj特殊的，特别		 adj特殊的，特别的",
"pat	[pæt]	 vt    (用掌或扁平物)轻拍，轻打",
"patch	[pætʃ]	 n 补钉，补片",
"hip	[hɪp]	 n.臀部，髋；屋脊",
"pave	[peɪv]	 vt铺路，铺砌，铺筑",
"hum	[hʌm]	  v.哼曲子；发嗡嗡声；忙碌n.嗡嗡声，嘈杂声",
"profound	[prə'faʊnd]	 adj很深的",
"prohibit	[prə(ʊ)'hɪbɪt]	 vt禁止",
"prolong	[prə'lɒŋ]	 vt延长，拉长，拖延",
"prominent	['prɒmɪnənt]	 adj突起的，凸出的",
"prompt	[prɒm(p)t]	adj 敏捷的，迅速的",
"pour	[pɔː]	 vt倒，注，灌，倾泻，涌流",
"preach	[priːtʃ]	 vi讲道，布道",
"preside	[prɪ'zaɪd]	 vt 主持，主管",
"press	[pres]	 vt按，挤，压",
"presume	[prɪ'zjuːm]	 vt推测，假定，假设",
"prevail	[prɪ'veɪl]	 vi流行，盛行",
"prey	[preɪ]	 n被捕食的动物，捕获物",
"prick	[prɪk]	 n 一刺，一扎",
"proceed	[prə'siːd]	 vi（尤指停顿或打断后）继续进行",
"proclaim	[prə'kleɪm]	 vt宣告，宣布，声明",
"propose	[prə'pəʊz]	 vt提议，建议",
"prosper	['prɒspə]	 vi 兴旺，繁荣，昌盛，成功",
"provoke	[prə'vəʊk]	 挑动，激起，导致",
"radiate	['reɪdɪeɪt]	 (光，热等）辐射，发射",
"radical	['rædɪk(ə)l]	 根本的，基本的",
"humiliate	[hjʊ'mɪlɪeɪt]	 v.使羞辱，使丢脸[同",
"lapse	[læps]	 n.失误；(时间的)流逝 vi.逐渐下降；终止",
"laptop	['læptɒp]	 n.小型计算机",
"perplex	[pə'pleks]	 vt 使困惑，使茫然",
"persecute	['pɜːsɪkjuːt]	 vt 虐待，残害，迫害",
"perspective	[pə'spektɪv]	 n透视画法，透视图",
"pessimistic	[,pesɪ'mɪstɪk]	 adj 悲观的",
"petition	[pɪ'tɪʃ(ə)n]	 n 请愿，请愿书",
"piercepɪəs]vt刺入，刺穿，穿		 vt 刺入，刺穿，穿透",
"pilot	['paɪlət]	 n 飞行员，驾驶员",
"pin	[pɪn]	 n 大头针，别针",
"pinch	[pɪn(t)ʃ]	 vt 捏，拧，夹",
"plausible	['plɔːzɪb(ə)l]	 adj 论点等貌似有理的",
"plead	[pliːd]	 vt恳求，请求",
"pledge	[pledʒ]	 n 保证，誓言，誓约",
"plot	[plɒt]	 n 小块土地",
"plug	[plʌg]	 n塞子，栓",
"plunge	[plʌn(d)ʒ]	 vt猛地投入或插入",
"pocket	['pɒkɪt]	 n 衣袋，口袋，袋子",
"polish	['pɒlɪʃ]	 vt 擦光，擦亮",
"poll	[pəʊl]	 n 民意测验",
"layman	['leɪmən]	 n.俗人，外行，门外汉",
"random	['rændəm]	 adj胡乱的，任意的，随意的",
"range	[reɪn(d)ʒ]	 n排，行，一系列",
"rank	[ræŋk]	 n排，行，列",
"rate	[reɪt]	 n比率，率",
"reap	[riːp]	 vt 收割，收获",
"rear	[rɪə]	  n 后部，后边，背部",
"recall	[rɪ'kɔːl]	vt回忆，回想",
"reciprocal	[rɪ'sɪprək(ə)l]	adj 相互的，交互的",
"reckon	['rek(ə)n]	 计算，数",
"hurl	[hɜːl]	 vt.猛投，力掷；大声叫骂",
"hurricane	['hʌrɪk(ə)n; -keɪn]	 n.飓风 ；十二级风",
"hypocrisy	[hɪ'pɒkrɪsɪ]	 n.伪善，虚伪",
"ideology	[,aɪdɪ'ɒlədʒɪ; ɪd-]	 n.意识形态，(政治或社会的)思想意识",
"infrastructure	['ɪnfrəstrʌktʃə]	  n.基础结构，基础设施",
"inhale	[ɪn'heɪl]	 v.吸入(气体等)，吸(烟",
"juvenile	['dʒuːvənaɪl]	 n.少年 a.青少年的，适合青少年的；幼稚的",
"kin	[kɪn]	 n.家族，亲属 a.亲属关系的",
"reclaim	[rɪ'kleɪm]	 vt 使改过，改造",
"recognize	['rɛkəg'naɪz]	 vt认出，识别",
"recollect	[,rekə'lekt]	 v 回忆，想起",
"recommend	[rekə'mend]	 vt 推荐，称赞",
"reconcile	['rek(ə)nsaɪl]	 vt 使和解，使和好",
"recover	[rɪ'kʌvə]	 vt 追回，重新得到",
"recruit	[rɪ'kruːt]	 vt 招募（新兵）招收（新成员",
"rectify	['rektɪfaɪ]	 vt纠正，改正，矫正",
"refer	[rɪ'fɜː]	 vt提到，谈到",
"refine	[rɪ'faɪn]	 vt提炼",
"pump	[pʌmp]	 n泵",
"pursue	[pə'sjuː]	 vt追赶，追随，追求",
"puzzle	['pʌz(ə)l]	 n难题，智力玩具，迷，迷惑",
"quality	['kwɒlɪtɪ]	 n 质量，品级",
"quantity	['kwɒntɪtɪ]	 n 数量，量",
"quench	[kwen(t)ʃ]	 vt 消除，平息，压制，扑灭",
"queue	[kjuː]	 n一队人，一行列车",
"quit	[kwɪt]	 vt停止，放弃",
"peculiar	[pɪ'kjuːlɪə]	 adj 奇怪的，古怪的",
"peel	[piːl]	 v 削皮，剥皮",
"penetrate	['penɪtreɪt]	 vt 穿透，渗入",
"perceive	[pə'siːv]	 vt 感知，感觉，觉察",
"perfect完美的，理想		perfect 完美的，理想的",
"perform	[pə'fɔːm]	 vt 做，执行，完成",
"Perfume	['pɜːfjuːm]	 n 香水，香料，香气",
"hop	[hɒp]	 v.人单足跳;跳上(车等)n.蹦跳;短程飞行",
"hound	[haʊnd]	 n.猎狗；卑鄙的人 vt.用猎狗追，追逐",
"housingn.住房，住房供给；(外、阀)壳，防护		housing n.住房，住房供给；(外、阀)壳，防护罩",
"hover	['hɒvə]	 vi. 盘旋；徘徊",
"howl	[haʊl]	 n.怒吼，嗥叫 vi.(风等)怒吼，咆哮",
"huddle	['hʌd(ə)l]	  vi.挤作一团；蜷缩vt.聚集n.挤在一起的人",
"quiver	['kwɪvə]	 vi 颤抖，抖动",
"quote	[kwəʊt]	 vt引用，引述，援引",
"rack	[ræk]	 n  架子，支架，搁架",
"reform	[rɪ'fɔːm]	 vt 改革，改良",
"refresh	[rɪ'freʃ]	 vt 使恢复活力，使振作精神",
"refute	[rɪ'fjuːt]	 vt驳斥，驳倒",
"regenerate	[rɪ'dʒenəreɪt]	 vt使恢复，使复兴，再生",
"regulate	['regjʊleɪt]	 vt管理，控制，为……制订规章",
"reign	[reɪn]	 vt 为王，统治",
"reinforce	[riːɪn'fɔːs]	 vt 增援，加强",
"rejoice	[rɪ'dʒɒɪs]	 vt 使感到高兴，使充满喜悦",
"relate	[rɪ'leɪt]	 vt 讲述，叙述",
"relay	['riːleɪ]	 vt接力传送，传递",
"release	[rɪ'liːs]	 vt 排放，释出",
"relevant	['relɪv(ə)nt]	 adj 有关的，切题的",
"relieve	[rɪ'liːv]	 vt缓解，减轻，解除",
"rescue	['reskjuː]	 vt 营救，救援，搭救",
"resent	[rɪ'zent]	 vt 怨恨",
"reserve	[rɪ'zɜːv]	 vt 保留，储备",
"resign	[rɪ'zaɪn]	 vt辞职，引退",
"resolve	[rɪ'zɒlv]	 vt 决定，打定注意要",
"Resort	[rɪ'zɔːt]	 vi 求助，凭借，诉诸",
"reverse	[rɪ'vɜːs]	 adj 相反的，颠倒的，倒退的",
"revise	[rɪ'vaɪz]	 vi 修订，校订",
"reviveɪ'vaɪv]vi苏醒，复		 vi 苏醒，复苏",
"ridiculous	[rɪ'dɪkjʊləs]	 adj 可笑的，荒唐的，荒谬的",
"rigid	['rɪdʒɪd]	 adj刚性的，坚硬的",
"ripe	[raɪp]	 adj 成熟的，时机成熟的",
"rot	[rɒt]	n 腐烂，腐坏，腐朽，腐败，腐化",
"roundabout	['raʊndəbaʊt]	 adj 绕道的，绕圈子的，不直接的",
"scan	[skæn]	 vt 细看，审视",
"scare	[skeə]	 vt 惊吓，恐惧",
"scatter	['skætə]	 vt撒，撒播",
"schedule	['ʃedjuːl; 'sked-]	 n时间表，进度表",
"scheme	[skiːm]	 n计划，方案",
"scold	[skəʊld]	vi 责骂，训斥",
"scorn	[skɔːn]	 vt轻蔑，鄙视",
"scrap	[skræp]	 n碎片，零屑",
"scrape	[skreɪp]	 vt 刮，擦",
"remark	[rɪ'mɑːk]	 vt评论，议论",
"remedy	['remɪdɪ]	 n 治疗，治疗法，药品",
"spectacle	['spektək(ə)l]	 n景象，奇观，壮观，场面",
"squeeze	[skwiːz]	 vt榨，挤",
"stern	[stɜːn]	 adj严厉的，苛刻的",
"stimulate	['stɪmjʊleɪt]	 vt刺激，促使",
"ignore	[ɪg'nɔː]	 vt 不顾，不理，忽视",
"illuminate	[ɪ'l(j)uːmɪneɪt]	 vt 照明，照亮，解释，启发，启迪",
"illustrate	['ɪləstreɪt]	  vt(用图或例子)说明，阐明",
"immerse	[ɪ'mɜːs]	 vt使浸没",
"shift转移，移		shift  转移，移动",
"shrewd	[ʃruːd]	 adj 机灵的，敏锐的，精明的",
"synchronize	['sɪŋkrənaɪz]	 vt使同步，使结合，使协调",
"taboo	[tə'buː]	 n禁忌，忌讳",
"tackle	['tæk(ə)l]	 n 用具，装备",
"transient	['trænzɪənt]	 adj短暂的，转瞬即逝的",
"simulate	['sɪmjʊleɪt]	 vt 假装，冒充",
"sketch	[sketʃ]	 n 素描，速写",
"slack	[slæk]	 adj 不紧的，不严的",
"slender	['slendə]	 adj苗条的，修长的，细长的",
"edible	['edɪb(ə)l]	 adj可以吃的,可食用的",
"elaborate	[ɪ'læb(ə)rət]	 adj精心计划(或制作)的,详尽的",
"elevate	['elɪveɪt]	 vt举起,提高,抬起",
"fascinate	['fæsɪneɪt]	 vt强烈的吸引,迷住,使神魂颠倒",
"emigrate	['emɪgreɪt]	 vi移居外国(或外地区",
"emit	[ɪ'mɪt]	 vt发出,散发(光,热,电度,声音,液体,气味等),发射电子",
"endeavor	[ɪn'dɛvɚ]	vt (为达到某一目的而)努力,尝试",
"compulsory	[kəm'pʌls(ə)rɪ]	 adj 必须做的，义务的",
"conceal	[kən'siːl]	 vt 隐藏，隐瞒，隐蔽",
"conceive	[kən'siːv]	 vt 构想出，设想",
"restore	[rɪ'stɔː]	 vt恢复，修复，康复",
"restrain	[rɪ'streɪn]	 vt抑制，遏止",
"resume	[rɪ'zjuːm]	 vt 重新开始，继续",
"rouse	[raʊz]	 vt 惊起",
"row	[rəʊ]	 n 吵闹，争吵",
"rub	[rʌb]	 vt擦，摩擦",
"rust	[rʌst]	 n锈，铁锈",
"ruthless	['ruːθlɪs]	 adj无情的，残忍的，冷酷的",
"sack	[sæk]	 n  麻袋，纸袋，塑料袋",
"sacred	['seɪkrɪd]	 adj神圣的",
"sacrifice	['sækrɪfaɪs]	 n献祭，供奉",
"salute	[sə'l(j)uːt]	 vt 敬礼，祝贺",
"retain	[rɪ'teɪn]	 vt保留，保持",
"reveal	[rɪ'viːl]	 vt 揭示，揭露",
"revengerevengevt报仇，复		revenge revenge vt报仇，复仇",
"concentrate	['kɒns(ə)ntreɪt]	 vt 集中，专心",
"condemn	[kən'dem]	vt 谴责",
"condense	[kən'dens]	 vt （使）压缩，（使）凝结，使简洁",
"confer	[kən'fɜː]	vt 商谈，商议",
"Confess	[kən'fes]	 vt  坦白，供认，承认，忏悔",
"formulate'fɔːmjʊleɪt]vt规划(制度等),构想出(计划方法		 vt规划(制度等),构想出(计划方法等",
"gallop	['gæləp]	 vi(马等的)飞跑，疾驰",
"gamble	['gæmb(ə)l]	 vi赌博",
"gasp	[gɑːsp]	 vi 喘气，喘息",
"gear	[gɪə]	 n齿轮，传动装置，(排)档",
"generalize	['dʒɛnrəlaɪz]	 vt 归纳，概括",
  };
#define EnglishWordCount (sizeof(EnglishWord)/sizeof(char *)) 
#endif